    -- Inserir Restaurantes
INSERT INTO custom_restaurantes (nome, endereco, telefone) VALUES
('Sabor da Terra', 'Av. João Naves de Ávila, 1234 - Santa Mônica, Uberlândia - MG', '(34) 3231-1234'),
('Churrascaria Boi na Brasa', 'R. Coronel Antônio Rios, 567 - Centro, Uberlândia - MG', '(34) 3232-5678'),
('Pizzaria Bella Napoli', 'Av. Rondon Pacheco, 890 - Tibery, Uberlândia - MG', '(34) 3233-9012'),
('Sushi House', 'R. Machado de Assis, 345 - Fundinho, Uberlândia - MG', '(34) 3234-3456'),
('Cantina Italiana', 'Av. Afonso Pena, 678 - Brasil, Uberlândia - MG', '(34) 3235-7890'),
('Restaurante Mineiro', 'R. Olegário Maciel, 901 - Centro, Uberlândia - MG', '(34) 3236-2345'),
('Hamburgueria Artesanal', 'Av. Getúlio Vargas, 234 - Aparecida, Uberlândia - MG', '(34) 3237-6789'),
('Bistrô Francês', 'R. Santos Dumont, 567 - Fundinho, Uberlândia - MG', '(34) 3238-0123'),
('Taco Mexicano', 'Av. Nicomedes Alves dos Santos, 890 - Gávea Sul, Uberlândia - MG', '(34) 3239-4567'),
('Restaurante Vegetariano Vida', 'R. Quintino Bocaiúva, 123 - Centro, Uberlândia - MG', '(34) 3240-8901'),
('Frutos do Mar Atlântico', 'Av. Aspirante Mega, 456 - Planalto, Uberlândia - MG', '(34) 3241-2345'),
('Churrascaria Gaúcha', 'R. Bernardo Guimarães, 789 - Martins, Uberlândia - MG', '(34) 3242-6789'),
('Comida Árabe Beirute', 'Av. Cesário Alvim, 012 - Brasil, Uberlândia - MG', '(34) 3243-0123'),
('Restaurante Oriental Dragon', 'R. Floriano Peixoto, 345 - Centro, Uberlândia - MG', '(34) 3244-4567'),
('Bistrô Contemporâneo', 'Av. João Pessoa, 678 - Saraiva, Uberlândia - MG', '(34) 3245-8901');

-- Inserir Categorias
INSERT INTO custom_categorias (nome) VALUES
('Entradas'),
('Saladas'),
('Sopas'),
('Pratos Principais'),
('Massas'),
('Pizzas'),
('Hambúrgueres'),
('Carnes'),
('Aves'),
('Peixes e Frutos do Mar'),
('Risotos'),
('Acompanhamentos'),
('Sobremesas'),
('Bebidas Quentes'),
('Bebidas Frias'),
('Sucos Naturais'),
('Drinks'),
('Vinhos'),
('Cervejas'),
('Porções');

-- Inserir Menus para cada restaurante
INSERT INTO custom_menus (fk_restaurante, nome, descricao) VALUES
-- Sabor da Terra
(1, 'Almoço Executivo', 'Menu especial para almoço de segunda a sexta'),
(1, 'Jantar à La Carte', 'Cardápio completo para jantar'),
(1, 'Menu Degustação', 'Seleção especial do chef'),
-- Churrascaria Boi na Brasa
(2, 'Rodízio de Carnes', 'Rodízio completo com cortes nobres'),
(2, 'À La Carte', 'Pratos individuais'),
-- Pizzaria Bella Napoli
(3, 'Pizzas Tradicionais', 'Pizzas clássicas italianas'),
(3, 'Pizzas Especiais', 'Criações do chef'),
(3, 'Menu Executivo', 'Pizza + bebida + sobremesa'),
-- Sushi House
(4, 'Rodízio de Sushi', 'Rodízio completo de comida japonesa'),
(4, 'Combinados', 'Combinações especiais'),
-- Cantina Italiana
(5, 'Almoço', 'Menu de almoço'),
(5, 'Jantar', 'Menu de jantar'),
-- Restaurante Mineiro
(6, 'Comida Caseira', 'Pratos típicos mineiros'),
(6, 'Menu do Dia', 'Prato do dia com entrada e sobremesa'),
-- Hamburgueria Artesanal
(7, 'Hambúrgueres', 'Hambúrgueres artesanais'),
(7, 'Combos', 'Combos com batata e bebida'),
-- Bistrô Francês
(8, 'Menu Executivo', 'Entrada, prato e sobremesa'),
(8, 'À La Carte', 'Cardápio completo'),
-- Taco Mexicano
(9, 'Tacos e Burritos', 'Pratos mexicanos tradicionais'),
(9, 'Menu Fiesta', 'Menu completo mexicano'),
-- Restaurante Vegetariano Vida
(10, 'Menu Vegano', 'Pratos 100% veganos'),
(10, 'Menu Vegetariano', 'Pratos vegetarianos'),
-- Frutos do Mar Atlântico
(11, 'Peixes e Frutos do Mar', 'Especialidades do mar'),
(11, 'Menu Degustação', 'Seleção do chef'),
-- Churrascaria Gaúcha
(12, 'Rodízio Premium', 'Rodízio com cortes especiais'),
(12, 'Rodízio Tradicional', 'Rodízio completo'),
-- Comida Árabe Beirute
(13, 'Pratos Árabes', 'Especialidades árabes'),
(13, 'Menu Executivo', 'Menu completo'),
-- Restaurante Oriental Dragon
(14, 'Pratos Chineses', 'Especialidades chinesas'),
(14, 'Pratos Tailandeses', 'Especialidades tailandesas'),
-- Bistrô Contemporâneo
(15, 'Menu Degustação', 'Experiência gastronômica completa'),
(15, 'À La Carte', 'Cardápio completo');

-- Inserir Itens de Cardápio
-- RESTAURANTE 1: Sabor da Terra (Menu 1, 2, 3)
INSERT INTO custom_itens_cardapio (fk_custom_menu, fk_custom_categoria, nome, descricao, preco, imagem_url) VALUES
(1, 1, 'Bruschetta Tradicional', 'Pão italiano com tomate, manjericão e azeite', 18.90, 'bruschetta.jpg'),
(1, 1, 'Bolinho de Mandioca', 'Bolinhos crocantes com geleia de pimenta', 22.90, 'bolinho_mandioca.jpg'),
(1, 1, 'Pastel de Queijo', 'Pastel folhado recheado com queijo minas', 16.90, 'pastel_queijo.jpg'),
(1, 2, 'Salada Caesar', 'Alface romana, croutons, parmesão e molho caesar', 28.90, 'caesar.jpg'),
(1, 2, 'Salada Caprese', 'Tomate, mussarela de búfala, manjericão e azeite', 32.90, 'caprese.jpg'),
(1, 3, 'Canja de Galinha', 'Canja caseira com arroz e legumes', 24.90, 'canja.jpg'),
(1, 3, 'Sopa de Cebola', 'Sopa gratinada com queijo gruyère', 28.90, 'sopa_cebola.jpg'),
(1, 4, 'Filé Mignon ao Molho Madeira', 'Filé mignon grelhado com molho madeira', 68.90, 'file_madeira.jpg'),
(1, 4, 'Picanha na Chapa', 'Picanha grelhada com arroz e batatas', 72.90, 'picanha.jpg'),
(1, 4, 'Costela ao Molho Barbecue', 'Costela assada lentamente', 65.90, 'costela_bbq.jpg'),
(1, 9, 'Frango à Parmegiana', 'Frango empanado com molho de tomate e queijo', 48.90, 'frango_parm.jpg'),
(1, 9, 'Supremo de Frango', 'Filé de frango recheado com queijo e presunto', 52.90, 'supremo.jpg'),
(1, 10, 'Salmão Grelhado', 'Salmão grelhado com molho de maracujá', 78.90, 'salmao.jpg'),
(1, 10, 'Tilápia ao Molho de Camarão', 'Filé de tilápia com molho de camarão', 58.90, 'tilapia.jpg'),
(1, 12, 'Arroz Branco', 'Arroz soltinho', 8.90, 'arroz.jpg'),
(1, 12, 'Batata Frita', 'Batatas fritas crocantes', 12.90, 'batata_frita.jpg'),
(1, 12, 'Purê de Batatas', 'Purê cremoso', 14.90, 'pure.jpg'),
(1, 12, 'Legumes Grelhados', 'Mix de legumes grelhados', 18.90, 'legumes.jpg'),
(1, 13, 'Petit Gateau', 'Bolinho de chocolate com sorvete', 24.90, 'petit_gateau.jpg'),
(1, 13, 'Pudim de Leite', 'Pudim caseiro', 18.90, 'pudim.jpg'),
(1, 13, 'Mousse de Maracujá', 'Mousse leve e refrescante', 16.90, 'mousse_maracuja.jpg'),
(1, 13, 'Torta de Limão', 'Torta com merengue', 22.90, 'torta_limao.jpg'),
(1, 14, 'Café Expresso', 'Café expresso tradicional', 6.90, 'expresso.jpg'),
(1, 14, 'Cappuccino', 'Cappuccino cremoso', 10.90, 'cappuccino.jpg'),
(1, 14, 'Chá Verde', 'Chá verde natural', 8.90, 'cha_verde.jpg'),
(1, 15, 'Refrigerante Lata', 'Coca-Cola, Guaraná, Fanta', 6.90, 'refri_lata.jpg'),
(1, 15, 'Água Mineral', 'Água mineral 500ml', 4.90, 'agua.jpg'),
(1, 15, 'Água com Gás', 'Água mineral com gás 500ml', 5.90, 'agua_gas.jpg'),
(1, 16, 'Suco de Laranja', 'Suco natural de laranja', 12.90, 'suco_laranja.jpg'),
(1, 16, 'Suco de Abacaxi com Hortelã', 'Suco refrescante', 14.90, 'suco_abacaxi.jpg'),
(1, 16, 'Limonada Suíça', 'Limonada cremosa', 13.90, 'limonada.jpg'),
(2, 4, 'Mignon com Fritas', 'Filé mignon com batatas fritas', 75.90, 'mignon_fritas.jpg'),
(2, 4, 'Bife à Cavalo', 'Bife com ovo frito e arroz', 58.90, 'bife_cavalo.jpg'),
(2, 5, 'Espaguete à Carbonara', 'Massa com bacon e creme', 48.90, 'carbonara.jpg'),
(2, 5, 'Penne ao Molho Rosé', 'Massa com molho rosé e frango', 52.90, 'penne_rose.jpg'),
(2, 11, 'Risoto de Camarão', 'Risoto cremoso com camarões', 68.90, 'risoto_camarao.jpg'),
(2, 11, 'Risoto de Funghi', 'Risoto com cogumelos variados', 62.90, 'risoto_funghi.jpg'),
(3, 1, 'Carpaccio de Salmão', 'Lâminas de salmão fresco', 45.90, 'carpaccio_salmao.jpg'),
(3, 1, 'Tábua de Frios', 'Seleção de queijos e frios', 58.90, 'tabua_frios.jpg'),
(3, 4, 'Cordeiro Assado', 'Carré de cordeiro com ervas', 98.90, 'cordeiro.jpg'),
(3, 4, 'Wellington de Carne', 'Filé wellington com massa folhada', 108.90, 'wellington.jpg');

-- RESTAURANTE 2: Churrascaria Boi na Brasa (Menu 4, 5)
INSERT INTO custom_itens_cardapio (fk_custom_menu, fk_custom_categoria, nome, descricao, preco, imagem_url) VALUES
(4, 8, 'Picanha', 'Picanha no ponto', 0.00, 'picanha_rodizio.jpg'),
(4, 8, 'Cupim', 'Cupim assado lentamente', 0.00, 'cupim.jpg'),
(4, 8, 'Maminha', 'Maminha suculenta', 0.00, 'maminha.jpg'),
(4, 8, 'Alcatra', 'Alcatra grelhada', 0.00, 'alcatra.jpg'),
(4, 8, 'Costela', 'Costela ao bafo', 0.00, 'costela.jpg'),
(4, 8, 'Fraldinha', 'Fraldinha macia', 0.00, 'fraldinha.jpg'),
(4, 8, 'Contrafilé', 'Contrafilé grelhado', 0.00, 'contrafile.jpg'),
(4, 8, 'Linguiça Artesanal', 'Linguiça temperada', 0.00, 'linguica.jpg'),
(4, 9, 'Coração de Frango', 'Coração grelhado', 0.00, 'coracao.jpg'),
(4, 9, 'Frango Assado', 'Frango inteiro assado', 0.00, 'frango_assado.jpg'),
(4, 9, 'Asa de Frango', 'Asa temperada', 0.00, 'asa_frango.jpg'),
(4, 10, 'Tilápia Grelhada', 'Tilápia com ervas', 0.00, 'tilapia_rodizio.jpg'),
(4, 10, 'Camarão ao Alho', 'Camarão no alho e óleo', 0.00, 'camarao_alho.jpg'),
(4, 2, 'Salada Completa', 'Buffet de saladas', 0.00, 'buffet_salada.jpg'),
(4, 12, 'Mandioca Frita', 'Mandioca crocante', 0.00, 'mandioca.jpg'),
(4, 12, 'Polenta Frita', 'Polenta crocante', 0.00, 'polenta.jpg'),
(4, 12, 'Farofa', 'Farofa de bacon', 0.00, 'farofa.jpg'),
(4, 12, 'Vinagrete', 'Molho vinagrete', 0.00, 'vinagrete.jpg'),
(4, 12, 'Arroz Branco', 'Arroz soltinho', 0.00, 'arroz_rodizio.jpg'),
(4, 12, 'Feijão', 'Feijão caseiro', 0.00, 'feijao.jpg'),
(4, 13, 'Abacaxi Grelhado', 'Abacaxi assado', 0.00, 'abacaxi.jpg'),
(4, 13, 'Sorvete', 'Sorvete variados', 0.00, 'sorvete.jpg'),
(4, 15, 'Refrigerante 2L', 'Refrigerante 2 litros', 12.90, 'refri_2l.jpg'),
(4, 19, 'Cerveja Pilsen', 'Cerveja gelada 600ml', 14.90, 'cerveja_pilsen.jpg'),
(4, 19, 'Cerveja IPA', 'Cerveja IPA 600ml', 18.90, 'cerveja_ipa.jpg'),
(5, 8, 'Picanha 500g', 'Picanha nobre 500g', 98.90, 'picanha_500.jpg'),
(5, 8, 'Filé Mignon 300g', 'Filé mignon grelhado', 82.90, 'file_300.jpg'),
(5, 8, 'Maminha 400g', 'Maminha grelhada', 72.90, 'maminha_400.jpg'),
(5, 8, 'Cupim 600g', 'Cupim assado', 88.90, 'cupim_600.jpg'),
(5, 20, 'Porção de Linguiça', 'Linguiça artesanal 500g', 42.90, 'porcao_linguica.jpg'),
(5, 20, 'Porção de Fraldinha', 'Fraldinha 400g', 56.90, 'porcao_fraldinha.jpg'),
(5, 20, 'Porção de Costela', 'Costela 600g', 68.90, 'porcao_costela.jpg'),
(5, 20, 'Porção de Coração', 'Coração de frango 400g', 38.90, 'porcao_coracao.jpg'),
(5, 12, 'Batata Rústica', 'Batata rústica assada', 24.90, 'batata_rustica.jpg'),
(5, 12, 'Mandioca com Bacon', 'Mandioca frita com bacon', 28.90, 'mandioca_bacon.jpg'),
(5, 2, 'Salada Caesar Especial', 'Caesar com frango grelhado', 38.90, 'caesar_especial.jpg'),
(5, 2, 'Salada Tropical', 'Mix de folhas com frutas', 34.90, 'salada_tropical.jpg'),
(5, 13, 'Brownie com Sorvete', 'Brownie quente com sorvete', 26.90, 'brownie.jpg'),
(5, 13, 'Churros', 'Churros com doce de leite', 22.90, 'churros.jpg'),
(5, 17, 'Caipirinha', 'Caipirinha tradicional', 18.90, 'caipirinha.jpg'),
(5, 17, 'Caipiroska', 'Caipiroska de frutas vermelhas', 22.90, 'caipiroska.jpg');

-- RESTAURANTE 3: Pizzaria Bella Napoli (Menu 6, 7, 8)
INSERT INTO custom_itens_cardapio (fk_custom_menu, fk_custom_categoria, nome, descricao, preco, imagem_url) VALUES
(6, 6, 'Pizza Margherita', 'Molho, mussarela, tomate e manjericão', 52.90, 'margherita.jpg'),
(6, 6, 'Pizza Calabresa', 'Molho, mussarela, calabresa e cebola', 54.90, 'calabresa.jpg'),
(6, 6, 'Pizza Mussarela', 'Molho e mussarela', 48.90, 'mussarela.jpg'),
(6, 6, 'Pizza Portuguesa', 'Molho, mussarela, presunto, ovos, cebola e azeitona', 58.90, 'portuguesa.jpg'),
(6, 6, 'Pizza Quatro Queijos', 'Molho e 4 queijos', 62.90, 'quatro_queijos.jpg'),
(6, 6, 'Pizza Napolitana', 'Molho, mussarela, tomate e parmesão', 56.90, 'napolitana.jpg'),
(6, 6, 'Pizza Frango com Catupiry', 'Molho, mussarela, frango e catupiry', 58.90, 'frango_catupiry.jpg'),
(6, 6, 'Pizza Pepperoni', 'Molho, mussarela e pepperoni', 64.90, 'pepperoni.jpg'),
(6, 6, 'Pizza Vegetariana', 'Molho, mussarela e legumes variados', 56.90, 'vegetariana.jpg'),
(6, 6, 'Pizza Atum', 'Molho, mussarela, atum e cebola', 62.90, 'atum.jpg'),
(7, 6, 'Pizza Carbonara', 'Molho branco, bacon, ovos e parmesão', 68.90, 'carbonara_pizza.jpg'),
(7, 6, 'Pizza Parma', 'Molho, mussarela, rúcula e presunto parma', 78.90, 'parma.jpg'),
(7, 6, 'Pizza Camarão', 'Molho, mussarela, camarão e alho', 82.90, 'camarao_pizza.jpg'),
(7, 6, 'Pizza Salmão', 'Molho branco, salmão e alcaparras', 84.90, 'salmao_pizza.jpg'),
(7, 6, 'Pizza Filé com Gorgonzola', 'Molho branco, filé e gorgonzola', 88.90, 'file_gorgonzola.jpg'),
(7, 6, 'Pizza Burrata', 'Molho, burrata, tomate e manjericão', 92.90, 'burrata_pizza.jpg'),
(7, 6, 'Pizza Trufa Negra', 'Molho branco, cogumelos e trufa', 98.90, 'trufa_pizza.jpg'),
(7, 6, 'Pizza Lombo Canadense', 'Molho, mussarela e lombo canadense', 72.90, 'lombo.jpg'),
(7, 6, 'Pizza Bacon', 'Molho, mussarela e bacon crocante', 68.90, 'bacon_pizza.jpg'),
(7, 6, 'Pizza Palmito', 'Molho, mussarela e palmito', 64.90, 'palmito.jpg'),
(8, 6, 'Pizza Média', 'Pizza de até 2 sabores', 58.90, 'pizza_media.jpg'),
(8, 15, 'Refrigerante 1L', 'Refrigerante 1 litro', 10.90, 'refri_1l.jpg'),
(8, 13, 'Tiramisù', 'Sobremesa italiana clássica', 22.90, 'tiramisu.jpg'),
(6, 1, 'Bruschetta Napolitana', 'Bruschetta com tomate fresco', 24.90, 'bruschetta_napoli.jpg'),
(6, 1, 'Porção de Pão de Alho', 'Pão de alho gratinado', 18.90, 'pao_alho.jpg'),
(6, 2, 'Salada Italiana', 'Mix de folhas com molho italiano', 32.90, 'salada_italiana.jpg'),
(7, 13, 'Pannacotta', 'Pannacotta com calda de frutas vermelhas', 26.90, 'pannacotta.jpg'),
(7, 13, 'Cannoli Siciliano', 'Cannoli recheado com ricota', 24.90, 'cannoli.jpg'),
(7, 18, 'Vinho Tinto Italiano', 'Taça de vinho tinto', 28.90, 'vinho_tinto.jpg'),
(7, 18, 'Vinho Branco Italiano', 'Taça de vinho branco', 26.90, 'vinho_branco.jpg'),
(6, 19, 'Cerveja Italiana', 'Peroni 330ml', 16.90, 'peroni.jpg'),
(6, 16, 'Suco de Limão', 'Suco natural de limão', 12.90, 'suco_limao.jpg'),
(6, 16, 'Limonada Italiana', 'Limonada com gengibre', 14.90, 'limonada_italiana.jpg'),
(7, 17, 'Negroni', 'Drink clássico italiano', 32.90, 'negroni.jpg'),
(7, 17, 'Spritz', 'Aperol spritz', 28.90, 'spritz.jpg'),
(8, 20, 'Porção de Batata Frita', 'Batata frita crocante', 22.90, 'batata_frita_porcao.jpg'),
(8, 20, 'Porção de Calabresa Acebolada', 'Calabresa com cebola', 38.90, 'calabresa_acebolada.jpg'),
(6, 14, 'Café Expresso Italiano', 'Expresso forte', 8.90, 'expresso_italiano.jpg'),
(6, 14, 'Cappuccino Italiano', 'Cappuccino cremoso', 12.90, 'cappuccino_italiano.jpg');

-- RESTAURANTE 4: Sushi House (Menu 9, 10)
INSERT INTO custom_itens_cardapio (fk_custom_menu, fk_custom_categoria, nome, descricao, preco, imagem_url) VALUES
(9, 10, 'Sashimi Salmão', '8 fatias de salmão', 0.00, 'sashimi_salmao.jpg'),
(9, 10, 'Sashimi Atum', '8 fatias de atum', 0.00, 'sashimi_atum.jpg'),
(9, 10, 'Sashimi White Fish', '8 fatias de peixe branco', 0.00, 'sashimi_white.jpg'),
(9, 10, 'Sushi Salmão', '8 unidades', 0.00, 'sushi_salmao.jpg'),
(9, 10, 'Sushi Atum', '8 unidades', 0.00, 'sushi_atum.jpg'),
(9, 10, 'Hot Roll Salmão', '8 unidades empanadas', 0.00, 'hot_salmao.jpg'),
(9, 10, 'Hot Roll Camarão', '8 unidades empanadas', 0.00, 'hot_camarao.jpg'),
(9, 10, 'Temaki Salmão', 'Cone de alga com salmão', 0.00, 'temaki_salmao.jpg'),
(9, 10, 'Temaki Skin', 'Cone com pele de salmão', 0.00, 'temaki_skin.jpg'),
(9, 10, 'Uramaki Philadelphia', 'Roll com cream cheese', 0.00, 'philadelphia.jpg'),
(9, 10, 'Uramaki California', 'Roll com kani e abacate', 0.00, 'california.jpg'),
(9, 10, 'Joy', 'Roll empanado especial', 0.00, 'joy.jpg'),
(9, 10, 'Harumaki', 'Rolinho primavera', 0.00, 'harumaki.jpg'),
(9, 10, 'Guioza', 'Pastel japonês frito', 0.00, 'guioza.jpg'),
(9, 10, 'Yakissoba', 'Macarrão frito com legumes', 0.00, 'yakissoba.jpg'),
(9, 1, 'Sunomono', 'Salada de pepino agridoce', 0.00, 'sunomono.jpg'),
(9, 1, 'Edamame', 'Vagem de soja cozida', 0.00, 'edamame.jpg'),
-- CONTINUAÇÃO RESTAURANTE 4: Sushi House (Menu 9, 10)
(9, 1, 'Tartar de Salmão', 'Salmão picado com molhos especiais', 0.00, 'tartar_salmao.jpg'),
(9, 1, 'Salmão Grelhado', 'Salmão grelhado com teriyaki', 0.00, 'salmao_grelhado.jpg'),
(9, 12, 'Missoshiru', 'Sopa de missô tradicional', 0.00, 'missoshiru.jpg'),
(9, 12, 'Gohan', 'Arroz japonês', 0.00, 'gohan.jpg'),
(9, 13, 'Tempura Sorvete', 'Sorvete frito crocante', 0.00, 'tempura_sorvete.jpg'),
(9, 13, 'Mochi', 'Bolinho de arroz recheado', 0.00, 'mochi.jpg'),
(9, 16, 'Suco de Maçã Verde', 'Suco natural refrescante', 0.00, 'suco_maca_verde.jpg'),
(9, 16, 'Chá Gelado', 'Chá verde gelado', 0.00, 'cha_gelado.jpg'),
(9, 19, 'Sake Quente', 'Sake tradicional aquecido', 0.00, 'sake_quente.jpg'),
(9, 19, 'Cerveja Japonesa', 'Asahi ou Kirin 330ml', 0.00, 'cerveja_japonesa.jpg'),

(10, 10, 'Combinado Sushi House', '15 peças variadas', 89.90, 'combinado_house.jpg'),
(10, 10, 'Combinado Executivo', '20 peças + temaki', 128.90, 'combinado_executivo.jpg'),
(10, 10, 'Combinado Premium', '30 peças variadas', 168.90, 'combinado_premium.jpg'),
(10, 10, 'Combinado Vegetariano', '15 peças veganas', 72.90, 'combinado_vegano.jpg'),
(10, 10, 'Barca Pequena', '40 peças para 2 pessoas', 198.90, 'barca_pequena.jpg'),
(10, 10, 'Barca Grande', '70 peças para 4 pessoas', 328.90, 'barca_grande.jpg'),
(10, 10, 'Temaki Especial', 'Temaki com salmão e cream cheese', 24.90, 'temaki_especial.jpg'),
(10, 10, 'Uramaki Especial', 'Roll com salmão grelhado', 38.90, 'uramaki_especial.jpg'),
(10, 1, 'Porção de Guioza', '6 unidades', 28.90, 'porcao_guioza.jpg'),
(10, 1, 'Porção de Harumaki', '8 unidades', 26.90, 'porcao_harumaki.jpg'),
(10, 1, 'Salada de Kani', 'Salada com kani e manga', 32.90, 'salada_kani.jpg'),
(10, 10, 'Yakissoba de Frango', 'Macarrão com frango e legumes', 45.90, 'yakissoba_frango.jpg'),
(10, 10, 'Yakissoba de Carne', 'Macarrão com carne e legumes', 48.90, 'yakissoba_carne.jpg'),
(10, 13, 'Dorayaki', 'Bolinho recheado com doce de feijão', 18.90, 'dorayaki.jpg'),
(10, 16, 'Suco de Pêssego', 'Suco natural de pêssego', 14.90, 'suco_pessego.jpg'),
(10, 19, 'Sake', 'Sake tradicional 300ml', 42.90, 'sake.jpg');

-- RESTAURANTE 5: Cantina Italiana (Menu 11, 12)
INSERT INTO custom_itens_cardapio (fk_custom_menu, fk_custom_categoria, nome, descricao, preco, imagem_url) VALUES
(11, 1, 'Antipasto Italiano', 'Seleção de frios e queijos italianos', 45.90, 'antipasto.jpg'),
(11, 1, 'Bruschetta al Pomodoro', 'Pão com tomate e manjericão', 22.90, 'bruschetta_pomodoro.jpg'),
(11, 1, 'Carpaccio di Manzo', 'Carpaccio de carne com rúcula', 38.90, 'carpaccio_manzo.jpg'),
(11, 2, 'Insalata Mista', 'Mix de folhas com tomate cereja', 28.90, 'insalata_mista.jpg'),
(11, 2, 'Insalata di Rucola', 'Rúcula com parmesão e tomate', 32.90, 'insalata_rucola.jpg'),
(11, 3, 'Zuppa di Pomodoro', 'Sopa cremosa de tomate', 24.90, 'zuppa_pomodoro.jpg'),
(11, 3, 'Minestrone', 'Sopa de legumes italiana', 26.90, 'minestrone.jpg'),
(11, 5, 'Spaghetti alla Carbonara', 'Espaguete com bacon e ovos', 48.90, 'spaghetti_carbonara.jpg'),
(11, 5, 'Fettuccine al Sugo', 'Fettuccine com molho de tomate', 42.90, 'fettuccine_sugo.jpg'),
(11, 5, 'Penne all''Arrabbiata', 'Penne com molho picante', 45.90, 'penne_arrabbiata.jpg'),
(11, 5, 'Lasagna alla Bolognese', 'Lasanha tradicional', 52.90, 'lasagna_bolognese.jpg'),
(11, 5, 'Risotto ai Funghi', 'Risoto com cogumelos', 56.90, 'risotto_funghi.jpg'),
(11, 4, 'Pollo alla Parmigiana', 'Frango à parmegiana', 58.90, 'pollo_parmigiana.jpg'),
(11, 4, 'Saltimbocca alla Romana', 'Filé com presunto e sálvia', 68.90, 'saltimbocca.jpg'),
(11, 4, 'Osso Buco', 'Bife de vitela com risoto', 78.90, 'osso_buco.jpg'),
(11, 12, 'Patate Arrosto', 'Batatas assadas com alecrim', 18.90, 'patate_arrosto.jpg'),
(11, 12, 'Verdure Grigliate', 'Legumes grelhados', 22.90, 'verdure_grigliate.jpg'),
(11, 13, 'Tiramisù Classico', 'Sobremesa italiana tradicional', 24.90, 'tiramisu_classico.jpg'),
(11, 13, 'Panna Cotta', 'Creme com calda de framboesa', 22.90, 'panna_cotta.jpg'),
(11, 13, 'Cannolo Siciliano', 'Cannoli com ricota', 26.90, 'cannolo_siciliano.jpg'),
(11, 14, 'Caffè Espresso', 'Café expresso italiano', 8.90, 'caffe_espresso.jpg'),
(11, 14, 'Cappuccino Italiano', 'Cappuccino tradicional', 12.90, 'cappuccino_italiano.jpg'),
(11, 18, 'Vino Rosso della Casa', 'Vinho tinto da casa', 32.90, 'vino_rosso.jpg'),
(11, 18, 'Vino Bianco della Casa', 'Vinho branco da casa', 30.90, 'vino_bianco.jpg'),

(12, 1, 'Arancini', 'Bolinho de risoto frito', 28.90, 'arancini.jpg'),
(12, 1, 'Focaccia', 'Pão italiano com azeite', 18.90, 'focaccia.jpg'),
(12, 5, 'Gnocchi al Pesto', 'Nhoque com molho pesto', 52.90, 'gnocchi_pesto.jpg'),
(12, 5, 'Ravioli di Ricotta', 'Ravioli com ricota e espinafre', 56.90, 'ravioli_ricotta.jpg'),
(12, 5, 'Tagliatelle al Tartufo', 'Tagliatelle com molho de trufa', 88.90, 'tagliatelle_tartufo.jpg'),
(12, 4, 'Bistecca alla Fiorentina', 'Bisteca à florentina', 128.90, 'bistecca_fiorentina.jpg'),
(12, 4, 'Branzino al Sale', 'Robalo assado no sal', 92.90, 'branzino_sale.jpg'),
(12, 11, 'Risotto alla Milanese', 'Risoto milanês com açafrão', 62.90, 'risotto_milanese.jpg'),
(12, 13, 'Semifreddo al Cioccolato', 'Semifreddo de chocolate', 28.90, 'semifreddo.jpg'),
(12, 13, 'Gelato Artigianale', 'Sorvete artesanal italiano', 24.90, 'gelato.jpg'),
(12, 17, 'Aperol Spritz', 'Drink italiano refrescante', 26.90, 'aperol_spritz.jpg'),
(12, 17, 'Negroni', 'Drink clássico italiano', 32.90, 'negroni_classico.jpg'),
(12, 18, 'Prosecco', 'Espumante italiano', 48.90, 'prosecco.jpg'),
(12, 18, 'Chianti Classico', 'Vinho tinto toscano', 65.90, 'chianti.jpg');

-- RESTAURANTE 6: Restaurante Mineiro (Menu 13, 14)
INSERT INTO custom_itens_cardapio (fk_custom_menu, fk_custom_categoria, nome, descricao, preco, imagem_url) VALUES
(13, 1, 'Pão de Queijo', 'Pão de queijo mineiro tradicional', 12.90, 'pao_de_queijo.jpg'),
(13, 1, 'Torresmo', 'Torresmo crocante caseiro', 18.90, 'torresmo.jpg'),
(13, 1, 'Bolinho de Mandioca', 'Bolinho de mandioca com queijo', 22.90, 'bolinho_mandioca_mineiro.jpg'),
(13, 1, 'Pastel de Angu', 'Pastel de angu com carne', 16.90, 'pastel_angu.jpg'),
(13, 2, 'Salada Mineira', 'Alface, tomate e cebola roxa', 24.90, 'salada_mineira.jpg'),
(13, 2, 'Couve à Mineira', 'Couve refogada com alho', 18.90, 'couve_mineira.jpg'),
(13, 3, 'Canja de Galinha Caipira', 'Canja caseira com galinha caipira', 26.90, 'canja_caipira.jpg'),
(13, 3, 'Sopa de Feijão', 'Sopa cremosa de feijão', 22.90, 'sopa_feijao.jpg'),
(13, 4, 'Feijão Tropeiro', 'Feijão tropeiro com torresmo', 38.90, 'feijao_tropeiro.jpg'),
(13, 4, 'Tutu à Mineira', 'Tutu com linguiça e ovos', 42.90, 'tutu_mineira.jpg'),
(13, 4, 'Frango com Quiabo', 'Frango caipira com quiabo', 48.90, 'frango_quiabo.jpg'),
(13, 4, 'Costelinha de Porco', 'Costelinha ao molho barbecue', 52.90, 'costelinha_porco.jpg'),
(13, 4, 'Leitão à Pururuca', 'Leitão com couve e farofa', 68.90, 'leitao_pururuca.jpg'),
(13, 4, 'Vaca Atolada', 'Costela com mandioca', 45.90, 'vaca_atolada.jpg'),
(13, 8, 'Picanha Mineira', 'Picanha com alho e sal grosso', 72.90, 'picanha_mineira.jpg'),
(13, 8, 'Contrafilé na Chapa', 'Contrafilé grelhado', 58.90, 'contrafile_chapa.jpg'),
(13, 9, 'Frango Caipira', 'Frango caipira com arroz', 46.90, 'frango_caipira.jpg'),
(13, 12, 'Arroz Branco', 'Arroz soltinho', 8.90, 'arroz_mineiro.jpg'),
(13, 12, 'Feijão Preto', 'Feijão preto caseiro', 12.90, 'feijao_preto.jpg'),
(13, 12, 'Polenta Frita', 'Polenta crocante', 14.90, 'polenta_mineira.jpg'),
(13, 12, 'Farofa de Bacon', 'Farofa caseira com bacon', 16.90, 'farofa_bacon.jpg'),
(13, 12, 'Angu', 'Angu cremoso', 12.90, 'angu.jpg'),
(13, 13, 'Doce de Leite', 'Doce de leite caseiro', 18.90, 'doce_leite.jpg'),
(13, 13, 'Goiabada Cascão', 'Goiabada com queijo', 22.90, 'goiabada_cascao.jpg'),
(13, 13, 'Pudim de Leite', 'Pudim de leite condensado', 20.90, 'pudim_leite.jpg'),
(13, 13, 'Ambrosia', 'Doce tradicional mineiro', 24.90, 'ambrosia.jpg'),
(13, 15, 'Cachaça Artesanal', 'Cachaça premium 50ml', 12.90, 'cachaca_artesanal.jpg'),
(13, 16, 'Caldo de Cana', 'Suco de cana natural', 14.90, 'caldo_cana.jpg'),
(13, 19, 'Cerveja Artesanal', 'Cerveja local 600ml', 22.90, 'cerveja_artesanal.jpg'),

(14, 4, 'Prato do Dia - Segunda', 'Feijoada completa', 45.90, 'feijoada.jpg'),
(14, 4, 'Prato do Dia - Terça', 'Frango com Quiabo', 42.90, 'prato_terca.jpg'),
(14, 4, 'Prato do Dia - Quarta', 'Costelinha com Angu', 48.90, 'prato_quarta.jpg'),
(14, 4, 'Prato do Dia - Quinta', 'Tutu à Mineira', 38.90, 'prato_quinta.jpg'),
(14, 4, 'Prato do Dia - Sexta', 'Peixe com Pirão', 52.90, 'prato_sexta.jpg'),
(14, 1, 'Entrada do Dia', 'Variável conforme o dia', 22.90, 'entrada_dia.jpg'),
(14, 13, 'Sobremesa do Dia', 'Variável conforme o dia', 18.90, 'sobremesa_dia.jpg'),
(14, 16, 'Suco do Dia', 'Suco natural variado', 12.90, 'suco_dia.jpg');

-- RESTAURANTE 7: Hamburgueria Artesanal (Menu 15, 16)
INSERT INTO custom_itens_cardapio (fk_custom_menu, fk_custom_categoria, nome, descricao, preco, imagem_url) VALUES
(15, 7, 'Hambúrguer Clássico', 'Pão, carne, queijo, alface, tomate', 28.90, 'classico.jpg'),
(15, 7, 'Hambúrguer Cheese', 'Carne, queijo cheddar, molho especial', 32.90, 'cheese.jpg'),
(15, 7, 'Hambúrguer Bacon', 'Carne, queijo, bacon crocante', 36.90, 'bacon_burger.jpg'),
(15, 7, 'Hambúrguer BBQ', 'Carne, queijo, cebola caramelizada, molho BBQ', 38.90, 'bbq_burger.jpg'),
(15, 7, 'Hambúrguer California', 'Carne, abacate, rúcula, maionese', 42.90, 'california.jpg'),
(15, 7, 'Hambúrguer Cheddar', 'Dupla carne, cheddar, bacon', 45.90, 'cheddar_burger.jpg'),
(15, 7, 'Hambúrguer Vegano', 'Hambúrguer de grão de bico', 34.90, 'vegano.jpg'),
(15, 7, 'Hambúrguer Frango', 'Frango empanado, alface, maionese', 35.90, 'frango_burger.jpg'),
(15, 7, 'Hambúrguer Picanha', 'Carne de picanha, queijo coalho', 48.90, 'picanha_burger.jpg'),
(15, 7, 'Hambúrguer Trufado', 'Carne wagyu, queijo brie, trufa', 68.90, 'trufado.jpg'),
(15, 20, 'Batata Frita Tradicional', 'Porção de batata frita', 18.90, 'batata_tradicional.jpg'),
(15, 20, 'Batata Frita Cheddar Bacon', 'Batata com cheddar e bacon', 28.90, 'batata_cheddar.jpg'),
(15, 20, 'Onion Rings', 'Anéis de cebola empanados', 22.90, 'onion_rings.jpg'),
(15, 20, 'Nuggets de Frango', '8 unidades de nuggets', 24.90, 'nuggets.jpg'),
(15, 1, 'Milk Shake Chocolate', 'Milk shake cremoso de chocolate', 22.90, 'shake_chocolate.jpg'),
(15, 1, 'Milk Shake Morango', 'Milk shake de morango', 22.90, 'shake_morango.jpg'),
(15, 1, 'Milk Shake Ovomaltine', 'Milk shake com ovomaltine', 24.90, 'shake_ovomaltine.jpg'),
(15, 15, 'Refrigerante 500ml', 'Coca, Guaraná, Fanta', 8.90, 'refri_500.jpg'),
(15, 16, 'Suco Natural 500ml', 'Laranja, Abacaxi, Limão', 12.90, 'suco_500.jpg'),

(16, 7, 'Combo Clássico', 'Hambúrguer + Batata + Refri', 42.90, 'combo_classico.jpg'),
(16, 7, 'Combo Cheese', 'Cheese + Batata + Refri', 46.90, 'combo_cheese.jpg'),
(16, 7, 'Combo Bacon', 'Bacon + Batata + Refri', 50.90, 'combo_bacon.jpg'),
(16, 7, 'Combo Duplo', '2 Hamburgueres + Batata + 2 Refris', 78.90, 'combo_duplo.jpg'),
(16, 7, 'Combo Família', '4 Hamburgueres + 2 Batatas + 4 Refris', 128.90, 'combo_familia.jpg'),
(16, 7, 'Combo Vegano', 'Vegano + Batata Doce + Suco', 48.90, 'combo_vegano.jpg'),
(16, 7, 'Combo Kids', 'Hambúrguer pequeno + Batata + Suco', 35.90, 'combo_kids.jpg'),
(16, 20, 'Combo Porções', 'Batata + Onion Rings + Nuggets', 58.90, 'combo_porcoes.jpg'),
(16, 13, 'Combo Sobremesa', 'Milk Shake + Brownie', 38.90, 'combo_sobremesa.jpg');

-- RESTAURANTE 8: Bistrô Francês (Menu 17, 18)
INSERT INTO custom_itens_cardapio (fk_custom_menu, fk_custom_categoria, nome, descricao, preco, imagem_url) VALUES
(17, 1, 'Soupe à l''Oignon', 'Sopa de cebola gratinada', 32.90, 'soupe_oignon.jpg'),
(17, 1, 'Escargots de Bourgogne', 'Caracóis ao alho e ervas', 45.90, 'escargots.jpg'),
(17, 1, 'Terrine de Campagne', 'Terrine de carne com geleia', 38.90, 'terrine.jpg'),
(17, 1, 'Foie Gras', 'Foie gras com torradas', 68.90, 'foie_gras.jpg'),
(17, 2, 'Salade Niçoise', 'Salada com atum e azeitonas', 42.90, 'salade_nicoise.jpg'),
(17, 2, 'Salade de Chèvre Chaud', 'Salada com queijo de cabra', 46.90, 'chevre_chaud.jpg'),
(17, 4, 'Coq au Vin', 'Galinha ao vinho tinto', 78.90, 'coq_au_vin.jpg'),
(17, 4, 'Boeuf Bourguignon', 'Boi ao vinho da Borgonha', 82.90, 'boeuf_bourguignon.jpg'),
(17, 4, 'Confit de Canard', 'Pato confit com batatas', 88.90, 'confit_canard.jpg'),
(17, 4, 'Ratatouille', 'Legumes provençais assados', 52.90, 'ratatouille.jpg'),
(17, 10, 'Moules Marinières', 'Mexilhões ao vinho branco', 65.90, 'moules_marinieres.jpg'),
(17, 10, 'Saumon en Croûte', 'Salmão em crosta de ervas', 72.90, 'saumon_croute.jpg'),
(17, 12, 'Gratin Dauphinois', 'Batatas gratinadas', 28.90, 'gratin_dauphinois.jpg'),
(17, 12, 'Haricots Verts', 'Vagem com amêndoas', 24.90, 'haricots_verts.jpg'),
(17, 13, 'Crème Brûlée', 'Creme queimado com baunilha', 26.90, 'creme_brulee.jpg'),
(17, 13, 'Tarte Tatin', 'Torta de maçã caramelizada', 32.90, 'tarte_tatin.jpg'),
(17, 13, 'Profiteroles', 'Bolinho com sorvete e chocolate', 34.90, 'profiteroles.jpg'),
(17, 13, 'Mousse au Chocolat', 'Mousse de chocolate francês', 24.90, 'mousse_chocolat.jpg'),
(17, 14, 'Café au Lait', 'Café com leite', 12.90, 'cafe_au_lait.jpg'),
(17, 14, 'Thé à la Menthe', 'Chá de menta marroquino', 14.90, 'the_menthe.jpg'),
(17, 18, 'Vin Rouge', 'Vinho tinto francês', 45.90, 'vin_rouge.jpg'),
(17, 18, 'Vin Blanc', 'Vinho branco francês', 42.90, 'vin_blanc.jpg'),
(17, 18, 'Champagne', 'Espumante francês', 98.90, 'champagne.jpg'),

(18, 1, 'Pâté de Campagne', 'Pâté caseiro com torradas', 36.90, 'pate_campagne.jpg'),
(18, 1, 'Tartare de Boeuf', 'Carne crua temperada', 48.90, 'tartare_boeuf.jpg'),
(18, 4, 'Filet Mignon au Poivre', 'Filé mignon ao molho de pimenta', 92.90, 'filet_poivre.jpg'),
(18, 4, 'Magret de Canard', 'Peito de pato com molho de laranja', 86.90, 'magret_canard.jpg'),
(18, 10, 'Bouillabaisse', 'Sopa de peixes provençal', 78.90, 'bouillabaisse.jpg'),
(18, 10, 'Homard Thermidor', 'Lagosta gratinada', 158.90, 'homard_thermidor.jpg'),
(18, 5, 'Quiche Lorraine', 'Torta de bacon e queijo', 42.90, 'quiche_lorraine.jpg'),
(18, 5, 'Croque Monsieur', 'Sanduíche gratinado', 38.90, 'croque_monsieur.jpg'),
(18, 11, 'Risotto aux Champignons', 'Risoto de cogumelos', 56.90, 'risotto_champignons.jpg'),
(18, 13, 'Soufflé au Chocolat', 'Sufllê de chocolate', 38.90, 'souffle_chocolat.jpg'),
(18, 13, 'Macarons', '6 unidades de macarons', 42.90, 'macarons.jpg'),
(18, 17, 'Kir Royal', 'Coquetel com champagne', 32.90, 'kir_royal.jpg'),
(18, 17, 'French 75', 'Coquetel clássico francês', 36.90, 'french_75.jpg'),
(18, 18, 'Bordeaux', 'Vinho Bordeaux tinto', 65.90, 'bordeaux.jpg'),
(18, 18, 'Sancerre', 'Vinho branco Sancerre', 58.90, 'sancerre.jpg');

-- RESTAURANTE 9: Taco Mexicano (Menu 19, 20)
INSERT INTO custom_itens_cardapio (fk_custom_menu, fk_custom_categoria, nome, descricao, preco, imagem_url) VALUES
(19, 4, 'Taco de Carne', '2 tacos com carne moída', 28.90, 'taco_carne.jpg'),
(19, 4, 'Taco de Frango', '2 tacos com frango desfiado', 26.90, 'taco_frango.jpg'),
(19, 4, 'Taco de Picanha', '2 tacos com picanha', 38.90, 'taco_picanha.jpg'),
(19, 4, 'Taco Vegano', '2 tacos com grão de bico', 24.90, 'taco_vegano.jpg'),
(19, 4, 'Burrito de Carne', 'Burrito grande com carne', 42.90, 'burrito_carne.jpg'),
(19, 4, 'Burrito de Frango', 'Burrito com frango', 38.90, 'burrito_frango.jpg'),
(19, 4, 'Quesadilla', 'Tortilla com queijo derretido', 32.90, 'quesadilla.jpg'),
(19, 4, 'Nachos Supreme', 'Nachos com guacamole e queijo', 45.90, 'nachos_supreme.jpg'),
(19, 4, 'Fajita Mixta', 'Fajitas de carne e frango', 68.90, 'fajita_mixta.jpg'),
(19, 1, 'Guacamole', 'Guacamole fresco com tortillas', 28.90, 'guacamole.jpg'),
(19, 1, 'Chili con Carne', 'Chili com carne e feijão', 34.90, 'chili_con_carne.jpg'),
(19, 1, 'Sopa de Tortilla', 'Sopa mexicana com tortilla', 26.90, 'sopa_tortilla.jpg'),
(19, 12, 'Arroz Mexicano', 'Arroz com milho e pimentão', 16.90, 'arroz_mexicano.jpg'),
(19, 12, 'Feijão Preto', 'Feijão preto temperado', 14.90, 'feijao_preto_mex.jpg'),
(19, 12, 'Elote', 'Milho na chapa com maionese', 22.90, 'elote.jpg'),
(19, 13, 'Churros Mexicanos', 'Churros com doce de leite', 24.90, 'churros_mexicanos.jpg'),
(19, 13, 'Flan de Coco', 'Pudim de coco caramelizado', 22.90, 'flan_coco.jpg'),
(19, 16, 'Horchata', 'Bebida mexicana de arroz', 18.90, 'horchata.jpg'),
(19, 16, 'Jamaica', 'Refresco de flor de hibisco', 16.90, 'jamaica.jpg'),
(19, 17, 'Margarita', 'Coquetel de tequila', 28.90, 'margarita.jpg'),
(19, 17, 'Mojito', 'Coquetel cubano', 26.90, 'mojito.jpg'),
(19, 19, 'Cerveza Corona', 'Cerveja mexicana', 18.90, 'corona.jpg'),
(19, 19, 'Tequila Shot', 'Tequila 50ml', 22.90, 'tequila_shot.jpg'),

(20, 4, 'Menu Fiesta Individual', 'Taco + Burrito + Nachos + Bebida', 68.90, 'menu_fiesta_individual.jpg'),
(20, 4, 'Menu Fiesta Duplo', '2 Tacos + 2 Burritos + Nachos + 2 Bebidas', 118.90, 'menu_fiesta_duplo.jpg'),
(20, 4, 'Menu Fiesta Familiar', '4 Tacos + 4 Burritos + Nachos Grande + 4 Bebidas', 198.90, 'menu_fiesta_familiar.jpg'),
(20, 4, 'Combo Tex-Mex', 'Fajita + Guacamole + Margarita', 88.90, 'combo_texmex.jpg'),
(20, 4, 'Combo Amigo', '2 Burritos + Nachos + 2 Bebidas', 92.90, 'combo_amigo.jpg'),
(20, 20, 'Porção de Nachos Grande', 'Nachos com todos os acompanhamentos', 58.90, 'nachos_grande.jpg'),
(20, 20, 'Porção de Wings', 'Asas de frango apimentadas', 42.90, 'wings.jpg'),
(20, 20, 'Porção de Queso Fundido', 'Queijo derretido com chorizo', 38.90, 'queso_fundido.jpg'),
(20, 13, 'Combo Sobremesa', 'Churros + Flan + 2 Cafés', 45.90, 'combo_sobremesa_mex.jpg'),
(20, 17, 'Combo Margarita', '3 Margaritas (sabores variados)', 75.90, 'combo_margarita.jpg');

-- RESTAURANTE 10: Restaurante Vegetariano Vida (Menu 21, 22)
INSERT INTO custom_itens_cardapio (fk_custom_menu, fk_custom_categoria, nome, descricao, preco, imagem_url) VALUES
(21, 1, 'Hummus com Pão Pita', 'Pasta de grão de bico com pão', 22.90, 'hummus_pita.jpg'),
(21, 1, 'Bruschetta de Tomate Seco', 'Bruschetta com tomate seco e manjericão', 24.90, 'bruschetta_tomate_seco.jpg'),
(21, 1, 'Bolinhos de Lentilha', 'Bolinhos de lentilha com iogurte', 26.90, 'bolinho_lentilha.jpg'),
(21, 2, 'Salada de Quinoa', 'Quinoa com legumes e molho de limão', 32.90, 'salada_quinoa.jpg'),
(21, 2, 'Salada Verde com Abacate', 'Mix de folhas com abacate e nozes', 34.90, 'salada_abacate.jpg'),
(21, 2, 'Salada de Grão de Bico', 'Grão de bico com hortelã e limão', 28.90, 'salada_grao_bico.jpg'),
(21, 3, 'Sopa de Abóbora', 'Sopa cremosa de abóbora com gengibre', 26.90, 'sopa_abobora.jpg'),
(21, 3, 'Sopa de Lentilha', 'Sopa de lentilha com legumes', 24.90, 'sopa_lentilha.jpg'),
(21, 4, 'Lasanha de Berinjela', 'Lasanha de berinjela com queijo vegano', 48.90, 'lasanha_berinjela.jpg'),
(21, 4, 'Hambúrguer de Grão de Bico', 'Hambúrguer vegano com batata doce', 42.90, 'burger_grao_bico.jpg'),
(21, 4, 'Risoto de Cogumelos', 'Risoto cremoso com cogumelos', 52.90, 'risoto_cogumelos_vegano.jpg'),
(21, 4, 'Tofu Grelhado', 'Tofu grelhado com molho teriyaki', 45.90, 'tofu_grelhado.jpg'),
(21, 4, 'Curry de Legumes', 'Curry com legumes e leite de coco', 46.90, 'curry_legumes.jpg'),
(21, 4, 'Quiche de Espinafre', 'Quiche de espinafre sem lactose', 38.90, 'quiche_espinafre.jpg'),
(21, 5, 'Espaguete de Abobrinha', 'Espaguete vegetal com molho pesto', 42.90, 'espaguete_abobrinha.jpg'),
(21, 5, 'Penne Integral ao Molho de Tomate', 'Penne integral com molho caseiro', 36.90, 'penne_integral.jpg'),
(21, 11, 'Risoto de Aspargos', 'Risoto com aspargos e limão siciliano', 54.90, 'risoto_aspargos.jpg'),
(21, 12, 'Purê de Batata Doce', 'Purê cremoso de batata doce', 18.90, 'pure_batata_doce.jpg'),
(21, 12, 'Legumes Grelhados', 'Mix de legumes da estação', 22.90, 'legumes_grelhados_vegano.jpg'),
(21, 12, 'Arroz Integral', 'Arroz integral com ervas', 14.90, 'arroz_integral.jpg'),
(21, 13, 'Mousse de Cacau', 'Mousse de cacau vegano', 24.90, 'mousse_cacau.jpg'),
(21, 13, 'Bolo de Cenoura', 'Bolo de cenoura com calda de chocolate', 22.90, 'bolo_cenoura_vegano.jpg'),
(21, 13, 'Pudim de Coco', 'Pudim de coco vegano', 26.90, 'pudim_coco.jpg'),
(21, 16, 'Suco Detox', 'Suco verde com couve e gengibre', 18.90, 'suco_detox.jpg'),
(21, 16, 'Suco de Beterraba', 'Suco de beterraba com laranja', 16.90, 'suco_beterraba.jpg'),
(21, 16, 'Chá Gelado de Pêssego', 'Chá gelado natural', 14.90, 'cha_gelado_pessego.jpg'),
(21, 14, 'Café com Leite de Amêndoas', 'Café com leite vegetal', 12.90, 'cafe_amendoas.jpg'),

(22, 1, 'Caponata de Berinjela', 'Berinjela com tomate e azeitonas', 28.90, 'caponata.jpg'),
(22, 1, 'Tábua de Queijos Vegetarianos', 'Seleção de queijos vegetarianos', 45.90, 'tabua_queijos_veg.jpg'),
(22, 2, 'Salada Caesar Vegetariana', 'Salada caesar com frango vegetal', 38.90, 'caesar_vegetariana.jpg'),
(22, 2, 'Salada de Beterraba', 'Beterraba com nozes e queijo de cabra', 36.90, 'salada_beterraba.jpg'),
(22, 4, 'Strogonoff de Cogumelos', 'Strogonoff de cogumelos com arroz', 52.90, 'strogonoff_cogumelos.jpg'),
(22, 4, 'Nhoque de Batata Doce', 'Nhoque com molho de tomate e manjericão', 46.90, 'nhoque_batata_doce.jpg'),
(22, 4, 'Torta de Legumes', 'Torta de legumes com massa integral', 42.90, 'torta_legumes.jpg'),
(22, 4, 'Escalope de Seitan', 'Seitan grelhado com molho madeira', 48.90, 'escalope_seitan.jpg'),
(22, 4, 'Falafel com Homus', 'Falafel com pasta de grão de bico', 44.90, 'falafel_homus.jpg'),
(22, 5, 'Ravioli de Ricota', 'Ravioli caseiro com molho sage', 56.90, 'ravioli_ricota_veg.jpg'),
(22, 5, 'Caneloni de Espinafre', 'Caneloni recheado com espinafre', 52.90, 'caneloni_espinafre.jpg'),
(22, 11, 'Risoto de Funghi', 'Risoto com cogumelos funghi', 58.90, 'risoto_funghi_veg.jpg'),
(22, 12, 'Couscous Marroquino', 'Couscous com frutas secas', 24.90, 'couscous_marroquino.jpg'),
(22, 12, 'Batatas Rústicas', 'Batatas assadas com alecrim', 20.90, 'batatas_rusticas_veg.jpg'),
(22, 13, 'Cheesecake de Frutas Vermelhas', 'Cheesecake vegetariano', 28.90, 'cheesecake_frutas.jpg'),
(22, 13, 'Torta de Maçã', 'Torta de maçã com canela', 26.90, 'torta_maca.jpg'),
(22, 13, 'Pavê de Chocolate', 'Pavê de chocolate vegetariano', 24.90, 'pave_chocolate.jpg'),
(22, 18, 'Vinho Orgânico', 'Vinho tinto orgânico', 42.90, 'vinho_organico.jpg'),
(22, 18, 'Espumante Vegetariano', 'Espumante sem produtos animais', 58.90, 'espumante_veg.jpg');

-- RESTAURANTE 11: Frutos do Mar Atlântico (Menu 23, 24)
INSERT INTO custom_itens_cardapio (fk_custom_menu, fk_custom_categoria, nome, descricao, preco, imagem_url) VALUES
(23, 1, 'Ceviche de Peixe Branco', 'Peixe marinado em limão', 45.90, 'ceviche_peixe.jpg'),
(23, 1, 'Bolinhos de Bacalhau', 'Bolinhos de bacalhau caseiros', 38.90, 'bolinho_bacalhau.jpg'),
(23, 1, 'Camarão ao Alho e Óleo', 'Camarão médio ao alho', 52.90, 'camarao_alho_oleo.jpg'),
(23, 1, 'Ostras Frescas', 'Ostras ao natural com limão', 68.90, 'ostras_frescas.jpg'),
(23, 1, 'Casquinha de Siri', 'Siri na casquinha gratinado', 42.90, 'casquinha_siri.jpg'),
(23, 2, 'Salada de Polvo', 'Polvo com vinagrete de limão', 48.90, 'salada_polvo.jpg'),
(23, 2, 'Salada de Algas', 'Algas marinhas com gergelim', 34.90, 'salada_algas.jpg'),
(23, 3, 'Caldeirada de Peixe', 'Sopa de peixe com legumes', 56.90, 'caldeirada.jpg'),
(23, 3, 'Sopa de Camarão', 'Sopa cremosa de camarão', 52.90, 'sopa_camarao.jpg'),
(23, 10, 'Moqueca de Peixe', 'Moqueca baiana com arroz', 78.90, 'moqueca_peixe.jpg'),
(23, 10, 'Moqueca de Camarão', 'Moqueca de camarão com dendê', 82.90, 'moqueca_camarao.jpg'),
(23, 10, 'Filé de Salmão Grelhado', 'Salmão com legumes grelhados', 72.90, 'salmao_grelhado_atlantico.jpg'),
(23, 10, 'Badejo ao Molho de Camarão', 'Badejo com molho especial', 68.90, 'badejo_camarao.jpg'),
(23, 10, 'Polvo à Lagareiro', 'Polvo com batatas e azeite', 76.90, 'polvo_lagareiro.jpg'),
(23, 10, 'Robalo ao Sal', 'Robalo assado no sal marinho', 88.90, 'robalo_sal.jpg'),
(23, 10, 'Lagosta Grelhada', 'Lagosta com manteiga de ervas', 158.90, 'lagosta_grelhada.jpg'),
(23, 10, 'Camarão na Moranga', 'Camarão na moranga com catupiry', 92.90, 'camarao_moranga.jpg'),
(23, 10, 'Peixe a la Plancha', 'Peixe do dia grelhado', 65.90, 'peixe_plancha.jpg'),
(23, 12, 'Arroz de Marisco', 'Arroz com frutos do mar', 32.90, 'arroz_marisco.jpg'),
(23, 12, 'Purê de Batata Baroa', 'Purê cremoso de batata baroa', 22.90, 'pure_baroa.jpg'),
(23, 12, 'Farofa de Dendê', 'Farofa baiana com dendê', 18.90, 'farofa_dende.jpg'),
(23, 12, 'Pirão de Peixe', 'Pirão com caldo de peixe', 24.90, 'pirao_peixe.jpg'),
(23, 12, 'Banana da Terra Frita', 'Banana da terra frita', 16.90, 'banana_terra.jpg'),
(23, 13, 'Pavê de Coco', 'Pavê de coco com calda de maracujá', 26.90, 'pave_coco.jpg'),
(23, 13, 'Mousse de Maracujá', 'Mousse de maracujá com calda', 22.90, 'mousse_maracuja_atlantico.jpg'),
(23, 13, 'Sorvete de Açaí', 'Sorvete de açaí com frutas', 28.90, 'sorvete_acai.jpg'),
(23, 16, 'Suco de Caju', 'Suco natural de caju', 18.90, 'suco_caju.jpg'),
(23, 16, 'Suco de Cupuaçu', 'Suco de cupuaçu cremoso', 20.90, 'suco_cupuacu.jpg'),
(23, 17, 'Caipirinha de Cachaça', 'Caipirinha tradicional', 24.90, 'caipirinha_atlantico.jpg'),
(23, 17, 'Caipirinha de Vodka', 'Caipiroska de frutas', 26.90, 'caipiroska_atlantico.jpg'),
(23, 19, 'Cerveja Artesanal', 'Cerveja local 600ml', 22.90, 'cerveja_artesanal_atlantico.jpg'),

(24, 10, 'Degustação de Frutos do Mar', 'Seleção de 5 pratos especiais', 198.90, 'degustacao_frutos_mar.jpg'),
(24, 10, 'Menu Mar e Terra', 'Lagosta + Filé Mignon', 168.90, 'menu_mar_terra.jpg'),
(24, 10, 'Menu do Chef Atlântico', 'Surpresa do chef com ingredientes frescos', 228.90, 'menu_chef_atlantico.jpg'),
(24, 10, 'Frutas do Mar para 2', 'Camarão, polvo, lula e peixe', 158.90, 'frutos_mar_2p.jpg'),
(24, 10, 'Rodízio de Frutos do Mar', 'Variedade de pratos por pessoa', 128.90, 'rodizio_frutos_mar.jpg'),
(24, 1, 'Entrada Degustação', '3 entradas da casa', 65.90, 'entrada_degustacao.jpg'),
(24, 13, 'Sobremesa Degustação', '3 sobremesas da casa', 45.90, 'sobremesa_degustacao.jpg'),
(24, 18, 'Harmonização de Vinhos', '3 taças de vinho harmonizadas', 85.90, 'harmonizacao_vinhos.jpg');

-- RESTAURANTE 12: Churrascaria Gaúcha (Menu 25, 26)
INSERT INTO custom_itens_cardapio (fk_custom_menu, fk_custom_categoria, nome, descricao, preco, imagem_url) VALUES
(25, 8, 'Picanha Premium', 'Picanha argentina no ponto', 0.00, 'picanha_premium.jpg'),
(25, 8, 'Costela Angus', 'Costela de angus assada lentamente', 0.00, 'costela_angus.jpg'),
(25, 8, 'Filé Mignon', 'Filé mignon suculento', 0.00, 'file_mignon_gaucho.jpg'),
(25, 8, 'Cordeiro', 'Cordeiro assado com ervas', 0.00, 'cordeiro_gaucho.jpg'),
(25, 8, 'Maminha de Primeira', 'Maminha selecionada', 0.00, 'maminha_primeira.jpg'),
(25, 8, 'Fraldinha Marinhada', 'Fraldinha com temperos especiais', 0.00, 'fraldinha_marinhada.jpg'),
(25, 8, 'Alcatra com Queijo', 'Alcatra recheada com queijo', 0.00, 'alcatra_queijo.jpg'),
(25, 8, 'Picanha com Alho', 'Picanha ao alho', 0.00, 'picanha_alho.jpg'),
(25, 9, 'Frango com Bacon', 'Frango envolto em bacon', 0.00, 'frango_bacon_gaucho.jpg'),
(25, 9, 'Peru Defumado', 'Peru defumado fatiado', 0.00, 'peru_defumado.jpg'),
(25, 10, 'Camarão na Chapa', 'Camarão grande na chapa', 0.00, 'camarao_chapa.jpg'),
(25, 10, 'Salmão Grelhado', 'Salmão com ervas finas', 0.00, 'salmao_gaucho.jpg'),
(25, 2, 'Buffet Premium', 'Buffet completo com iguarias', 0.00, 'buffet_premium.jpg'),
(25, 12, 'Arroz de Carreteiro', 'Arroz gaúcho com carne seca', 0.00, 'arroz_carreteiro.jpg'),
(25, 12, 'Polenta Cremosa', 'Polenta com queijo', 0.00, 'polenta_cremosa.jpg'),
(25, 12, 'Maionese Caseira', 'Maionese da casa', 0.00, 'maionese_caseira.jpg'),
(25, 12, 'Beringela à Parmegiana', 'Beringela gratinada', 0.00, 'beringela_parmegiana.jpg'),
(25, 13, 'Pavê de Chocolate Belga', 'Pavê premium', 0.00, 'pave_chocolate_belga.jpg'),
(25, 13, 'Cheesecake de Frutas', 'Cheesecake com calda', 0.00, 'cheesecake_frutas_gaucho.jpg'),
(25, 13, 'Sorvetes Italianos', 'Sorvetes premium', 0.00, 'sorvetes_italianos.jpg'),
(25, 15, 'Refrigerante Importado', 'Refrigerantes premium', 12.90, 'refri_importado.jpg'),
(25, 19, 'Cerveja Artesanal Gaúcha', 'Cervejas especiais', 24.90, 'cerveja_gaucha.jpg'),
(25, 18, 'Vinhos Premium', 'Vinhos selecionados', 45.90, 'vinhos_premium.jpg'),
(25, 17, 'Drinks Especiais', 'Coquetéis exclusivos', 28.90, 'drinks_especiais.jpg'),

(26, 8, 'Picanha', 'Picanha tradicional', 0.00, 'picanha_tradicional.jpg'),
(26, 8, 'Alcatra', 'Alcatra grelhada', 0.00, 'alcatra_tradicional.jpg'),
(26, 8, 'Costela', 'Costela ao fogo de chão', 0.00, 'costela_tradicional.jpg'),
(26, 8, 'Fraldinha', 'Fraldinha macia', 0.00, 'fraldinha_tradicional.jpg'),
(26, 8, 'Cupim', 'Cupim assado', 0.00, 'cupim_tradicional.jpg'),
(26, 8, 'Linguiça', 'Linguiça caseira', 0.00, 'linguica_tradicional.jpg'),
(26, 9, 'Coração de Frango', 'Coração temperado', 0.00, 'coracao_tradicional.jpg'),
(26, 9, 'Asa de Frango', 'Asa com molho barbecue', 0.00, 'asa_tradicional.jpg'),
(26, 9, 'Sobrecoxa', 'Sobrecoxa desossada', 0.00, 'sobrecoxa.jpg'),
(26, 2, 'Buffet de Saladas', 'Variedade de saladas', 0.00, 'buffet_saladas_tradicional.jpg'),
(26, 12, 'Arroz Branco', 'Arroz soltinho', 0.00, 'arroz_tradicional.jpg'),
(26, 12, 'Feijão Preto', 'Feijão preto', 0.00, 'feijao_tradicional.jpg'),
(26, 12, 'Farofa', 'Farofa da casa', 0.00, 'farofa_tradicional.jpg'),
(26, 12, 'Vinagrete', 'Vinagrete caseiro', 0.00, 'vinagrete_tradicional.jpg'),
(26, 12, 'Batata Frita', 'Batata frita crocante', 0.00, 'batata_tradicional.jpg'),
(26, 13, 'Pudim', 'Pudim de leite', 0.00, 'pudim_tradicional.jpg'),
(26, 13, 'Gelatina', 'Gelatina colorida', 0.00, 'gelatina.jpg'),
(26, 13, 'Fruta da Estação', 'Frutas frescas', 0.00, 'frutas_estacao.jpg'),
(26, 15, 'Refrigerante', 'Refrigerante 2L', 14.90, 'refri_2l_tradicional.jpg'),
(26, 16, 'Suco Natural', 'Suco da fruta 1L', 18.90, 'suco_1l.jpg'),
(26, 19, 'Cerveja Nacional', 'Cerveja 600ml', 16.90, 'cerveja_nacional.jpg'),
(26, 17, 'Caipirinha', 'Caipirinha tradicional', 20.90, 'caipirinha_tradicional.jpg');

-- RESTAURANTE 13: Comida Árabe Beirute (Menu 27, 28)
INSERT INTO custom_itens_cardapio (fk_custom_menu, fk_custom_categoria, nome, descricao, preco, imagem_url) VALUES
(27, 4, 'Kibe Frito', '10 unidades de kibe', 32.90, 'kibe_frito.jpg'),
(27, 4, 'Kibe Assado', 'Kibe assado no forno', 36.90, 'kibe_assado.jpg'),
(27, 4, 'Esfiha de Carne', '6 unidades de esfiha', 24.90, 'esfiha_carne.jpg'),
(27, 4, 'Esfiha de Queijo', '6 unidades de esfiha de queijo', 22.90, 'esfiha_queijo.jpg'),
(27, 4, 'Shawarma de Carne', 'Pão sírio com carne', 28.90, 'shawarma_carne.jpg'),
(27, 4, 'Shawarma de Frango', 'Pão sírio com frango', 26.90, 'shawarma_frango.jpg'),
(27, 4, 'Quibe Cru', 'Quibe cru temperado', 38.90, 'quibe_cru.jpg'),
(27, 4, 'Fatayer', 'Pastelzinho árabe de espinafre', 29.90, 'fatayer.jpg'),
(27, 1, 'Homus', 'Pasta de grão de bico', 24.90, 'homus_arabe.jpg'),
(27, 1, 'Baba Ghanoush', 'Pasta de berinjela', 26.90, 'baba_ghanoush.jpg'),
(27, 1, 'Tabule', 'Salada de trigo com hortelã', 22.90, 'tabule.jpg'),
(27, 1, 'Salada de Grão de Bico', 'Grão de bico com tahine', 28.90, 'salada_grao_bico_arabe.jpg'),
(27, 1, 'Kofta', 'Espetinho de carne temperada', 34.90, 'kofta.jpg'),
(27, 1, 'Sambusek', 'Pastel árabe com carne', 26.90, 'sambusek.jpg'),
(27, 2, 'Salada Árabe', 'Alface, tomate, pepino e limão', 20.90, 'salada_arabe.jpg'),
(27, 2, 'Fattoush', 'Salada com pão sírio crocante', 24.90, 'fattoush.jpg'),
(27, 4, 'Mandi com Frango', 'Arroz com frango e amêndoas', 45.90, 'mandi_frango.jpg'),
(27, 4, 'Mandi com Carne', 'Arroz com carne e pinoli', 48.90, 'mandi_carne.jpg'),
(27, 4, 'Cuscuz Marroquino', 'Cuscuz com legumes', 42.90, 'cuscuz_marroquino_arabe.jpg'),
(27, 12, 'Arroz Árabe', 'Arroz com nozes e passas', 18.90, 'arroz_arabe.jpg'),
(27, 12, 'Pão Sírio', 'Pão sírio tradicional', 8.90, 'pao_sirio.jpg'),
(27, 13, 'Baklava', 'Doce folhado com nozes', 22.90, 'baklava.jpg'),
(27, 13, 'Kunafa', 'Doce com queijo e açafrão', 26.90, 'kunafa.jpg'),
(27, 13, 'Maamoul', 'Biscoito recheado com tâmara', 24.90, 'maamoul.jpg'),
(27, 13, 'Halawa', 'Doce de gergelim', 20.90, 'halawa.jpg'),
(27, 16, 'Suco de Tamarindo', 'Suco de tamarindo natural', 16.90, 'suco_tamarindo.jpg'),
(27, 16, 'Laban', 'Bebida de iogurte', 14.90, 'laban.jpg'),
(27, 14, 'Café Árabe', 'Café árabe tradicional', 12.90, 'cafe_arabe.jpg'),
(27, 14, 'Chá de Mentha', 'Chá de hortelã marroquino', 10.90, 'cha_mentha.jpg'),

(28, 4, 'Menu Executivo Carne', 'Kibe + Shawarma + Suco', 52.90, 'menu_executivo_carne.jpg'),
(28, 4, 'Menu Executivo Frango', 'Esfiha + Shawarma Frango + Suco', 48.90, 'menu_executivo_frango.jpg'),
(28, 4, 'Menu Executivo Vegetariano', 'Fatayer + Homus + Tabule + Suco', 46.90, 'menu_executivo_veg.jpg'),
(28, 4, 'Menu Beirute Completo', 'Entrada + Prato Principal + Sobremesa + Bebida', 68.90, 'menu_beirute_completo.jpg'),
(28, 4, 'Menu Família', '4 Shawarmas + Kibe + Homus + 4 Bebidas', 128.90, 'menu_familia_arabe.jpg'),
(28, 20, 'Porção de Kibe', '15 unidades de kibe frito', 45.90, 'porcao_kibe.jpg'),
(28, 20, 'Porção de Esfiha', '12 unidades variadas', 38.90, 'porcao_esfiha.jpg'),
(28, 20, 'Tábua Árabe', 'Seleção de entradas árabes', 65.90, 'tabua_arabe.jpg'),
(28, 20, 'Porção de Shawarma', '3 unidades de shawarma', 42.90, 'porcao_shawarma.jpg'),
(28, 13, 'Combo de Doces Árabes', '4 tipos de doces árabes', 35.90, 'combo_doces_arabes.jpg'),
(28, 16, 'Jarra de Suco Natural', 'Jarra 1L de suco', 24.90, 'jarra_suco.jpg'),
(28, 19, 'Cerveja Importada', 'Cerveja importada 330ml', 18.90, 'cerveja_importada.jpg');

-- RESTAURANTE 14: Restaurante Oriental Dragon (Menu 29, 30)
INSERT INTO custom_itens_cardapio (fk_custom_menu, fk_custom_categoria, nome, descricao, preco, imagem_url) VALUES
(29, 4, 'Frango Xadrez', 'Frango com legumes e castanhas', 42.90, 'frango_xadrez.jpg'),
(29, 4, 'Frango Agridoce', 'Frango com molho agridoce', 38.90, 'frango_agridoce.jpg'),
(29, 4, 'Frango com Amêndoas', 'Frango com amêndoas e legumes', 45.90, 'frango_amendoas.jpg'),
(29, 4, 'Carne Xadrez', 'Carne com legumes e pimentão', 46.90, 'carne_xadrez.jpg'),
(29, 4, 'Carne com Brócolis', 'Carne com brócolis e molho oyster', 44.90, 'carne_brocolis.jpg'),
(29, 4, 'Porco Agridoce', 'Lombo com molho agridoce', 42.90, 'porco_agridoce.jpg'),
(29, 4, 'Camarrão Xadrez', 'Camarrão com legumes', 58.90, 'camarao_xadrez.jpg'),
(29, 4, 'Camarrão Empanado', 'Camarrão empanado com molho', 52.90, 'camarao_empanado.jpg'),
(29, 4, 'Yakissoba de Carne', 'Macarrão frito com carne', 48.90, 'yakissoba_carne_chines.jpg'),
(29, 4, 'Yakissoba de Frango', 'Macarrão frito com frango', 46.90, 'yakissoba_frango_chines.jpg'),
(29, 4, 'Yakissoba Misto', 'Macarrão com carne e frango', 52.90, 'yakissoba_misto.jpg'),
(29, 4, 'Lula à Chinesa', 'Lula com molho de ostras', 54.90, 'lula_chinesa.jpg'),
(29, 4, 'Pato à Pequim', 'Pato lacado com pancakes', 88.90, 'pato_pequim.jpg'),
(29, 4, 'Porco com Molho Hoisin', 'Lombo com molho hoisin', 48.90, 'porco_hoisin.jpg'),
(29, 1, 'Rolinho Primavera', '4 unidades de rolinho primavera', 24.90, 'rolinho_primavera.jpg'),
(29, 1, 'Bolinho de Camarrão', '4 unidades de bolinho', 28.90, 'bolinho_camarao_chines.jpg'),
(29, 1, 'Guioza', '6 unidades de guioza', 26.90, 'guioza_chines.jpg'),
(29, 1, 'Sopa de Wonton', 'Sopa com pastéis chineses', 22.90, 'sopa_wonton.jpg'),
(29, 1, 'Salada de Algas', 'Algas marinhas com gergelim', 20.90, 'salada_algas_chines.jpg'),
(29, 12, 'Arroz Frito', 'Arroz frito com legumes', 18.90, 'arroz_frito.jpg'),
(29, 12, 'Arroz Branco', 'Arroz jasmim', 12.90, 'arroz_jasmim.jpg'),
(29, 12, 'Macarrão Frito', 'Macarrão frito simples', 22.90, 'macarrao_frito.jpg'),
(29, 13, 'Banana Frita', 'Banana empanada com mel', 24.90, 'banana_frita_chines.jpg'),
(29, 13, 'Pudim de Manga', 'Pudim de manga com coco', 26.90, 'pudim_manga.jpg'),
(29, 16, 'Suco de Lychee', 'Suco de lychee natural', 18.90, 'suco_lychee.jpg'),
(29, 16, 'Chá Verde Gelado', 'Chá verde com limão', 14.90, 'cha_verde_gelado.jpg'),
(29, 14, 'Chá de Jasmim', 'Chá de jasmim tradicional', 10.90, 'cha_jasmim.jpg'),
(29, 19, 'Cerveja Chinesa', 'Cerveja Tsingtao', 16.90, 'tsingtao.jpg'),

(30, 4, 'Pad Thai', 'Macarrão tailandês com camarão', 56.90, 'pad_thai.jpg'),
(30, 4, 'Curry Verde Tailandês', 'Curry verde com frango', 52.90, 'curry_verde.jpg'),
(30, 4, 'Curry Vermelho Tailandês', 'Curry vermelho com carne', 54.90, 'curry_vermelho.jpg'),
(30, 4, 'Curry Massaman', 'Curry massaman com amendoim', 58.90, 'curry_massaman.jpg'),
(30, 4, 'Tom Yum Goong', 'Sopa tailandesa com camarão', 46.90, 'tom_yum.jpg'),
(30, 4, 'Tom Kha Gai', 'Sopa de coco com frango', 44.90, 'tom_kha_gai.jpg'),
(30, 4, 'Satay de Frango', 'Espetinho de frango com amendoim', 38.90, 'satay_frango.jpg'),
(30, 4, 'Larb Gai', 'Salada de frango picante', 42.90, 'larb_gai.jpg'),
(30, 4, 'Som Tam', 'Salada de papaia verde', 36.90, 'som_tam.jpg'),
(30, 4, 'Khao Pad', 'Arroz frito tailandês', 32.90, 'khao_pad.jpg'),
(30, 4, 'Pad Kra Pao', 'Carne moída com manjericão', 48.90, 'pad_kra_pao.jpg'),
(30, 4, 'Peixe ao Molho de Tamarindo', 'Peixe inteiro com tamarindo', 68.90, 'peixe_tamarindo.jpg'),
(30, 4, 'Camarão ao Molho de Coco', 'Camarão com leite de coco', 62.90, 'camarao_coco.jpg'),
(30, 1, 'Porção de Spring Rolls', '4 unidades de spring rolls', 28.90, 'spring_rolls.jpg'),
(30, 1, 'Porção de Fish Cakes', 'Bolinho de peixe tailandês', 32.90, 'fish_cakes.jpg'),
(30, 1, 'Porção de Tod Mun', 'Bolinho de curry tailandês', 26.90, 'tod_mun.jpg'),
(30, 12, 'Arroz Jasmine', 'Arroz tailandês jasmine', 14.90, 'arroz_jasmine.jpg'),
(30, 12, 'Arroz Pegajoso', 'Arroz glutinoso', 16.90, 'arroz_pegajoso.jpg'),
(30, 13, 'Mango Sticky Rice', 'Arroz doce com manga', 28.90, 'mango_sticky_rice.jpg'),
(30, 13, 'Coconut Ice Cream', 'Sorvete de coco tailandês', 24.90, 'coconut_ice_cream.jpg'),
(30, 16, 'Suco de Coco Verde', 'Água de coco natural', 18.90, 'suco_coco_verde.jpg'),
(30, 16, 'Cha Yen', 'Chá tailandês gelado', 16.90, 'cha_yen.jpg'),
(30, 19, 'Cerveja Tailandesa', 'Cerveja Singha', 18.90, 'singha.jpg'),
(30, 17, 'Mojito Tailandês', 'Mojito com limão siciliano', 26.90, 'mojito_tailandes.jpg');

-- RESTAURANTE 15: Bistrô Contemporâneo (Menu 31, 32)
INSERT INTO custom_itens_cardapio (fk_custom_menu, fk_custom_categoria, nome, descricao, preco, imagem_url) VALUES
(31, 1, 'Amuse-bouche do Chef', 'Surpresa do chef para abrir o apetite', 0.00, 'amuse_bouche.jpg'),
(31, 1, 'Tartar de Salmão com Abacate', 'Salmão picado com abacate e wasabi', 45.90, 'tartar_salmao_abacate.jpg'),
(31, 1, 'Carpaccio de Beterraba', 'Beterraba com queijo de cabra e nozes', 38.90, 'carpaccio_beterraba.jpg'),
(31, 1, 'Foie Gras com Geleia de Porto', 'Foie gras com geleia e torradas', 68.90, 'foie_gras_porto.jpg'),
(31, 2, 'Salada de Rúcula com Pera', 'Rúcula, pera caramelizada e nozes', 42.90, 'salada_rucula_pera.jpg'),
(31, 2, 'Salada de Quinoa com Edamame', 'Quinoa, edamame e molho de gengibre', 46.90, 'salada_quinoa_edamame.jpg'),
(31, 3, 'Sopa de Abóbora com Gengibre', 'Sopa cremosa com toque picante', 32.90, 'sopa_abobora_gengibre.jpg'),
(31, 3, 'Consommé de Cogumelos', 'Caldo claro de cogumelos silvestres', 36.90, 'consomme_cogumelos.jpg'),
(31, 4, 'Filé Mignon com Purê de Aipo', 'Filé mignon com purê de aipo e redução', 92.90, 'file_mignon_apoio.jpg'),
(31, 4, 'Risoto de Trufa Negra', 'Risoto com trufa negra fresca', 78.90, 'risoto_trufa_negra.jpg'),
(31, 4, 'Salmão com Crosta de Gergelim', 'Salmão com gergelim e molho de soja', 72.90, 'salmao_gergelim.jpg'),
(31, 4, 'Confit de Pato com Laranja', 'Pato confit com molho de laranja', 88.90, 'confit_pato_laranja.jpg'),
(31, 4, 'Medalhão de Vitela com Funghi', 'Vitela com cogumelos e vinho', 98.90, 'medalhao_vitela.jpg'),
(31, 10, 'Saint Peter com Cuscuz', 'Filé de saint peter com cuscuz marroquino', 76.90, 'saint_peter_cuscuz.jpg'),
(31, 10, 'Polvo com Batata Doce', 'Polvo grelhado com purê de batata doce', 82.90, 'polvo_batata_doce.jpg'),
(31, 11, 'Risoto de Aspargos Brancos', 'Risoto com aspargos brancos e parmesão', 65.90, 'risoto_aspargos_brancos.jpg'),
(31, 12, 'Legumes Assados com Ervas', 'Legumes da estação com ervas finas', 28.90, 'legumes_assados_ervas.jpg'),
(31, 12, 'Purê de Batata com Trufa', 'Purê de batata com azeite de trufa', 32.90, 'pure_batata_trufa.jpg'),
(31, 13, 'Soufflé de Chocolate', 'Soufflé de chocolate belga', 38.90, 'souffle_chocolate_contemporaneo.jpg'),
(31, 13, 'Panna Cotta de Baunilha', 'Panna cotta com frutas vermelhas', 34.90, 'panna_cotta_baunilha.jpg'),
(31, 13, 'Tarte Tatin de Maçã', 'Tarte tatin com sorvete de baunilha', 36.90, 'tarte_tatin_maca.jpg'),
(31, 13, 'Selection de Queijos', 'Seleção de queijos com geleias', 45.90, 'selection_queijos.jpg'),
(31, 18, 'Harmonização - Primeira Taça', 'Vinho para entrada', 35.90, 'vinho_entrada.jpg'),
(31, 18, 'Harmonização - Segunda Taça', 'Vinho para prato principal', 42.90, 'vinho_principal.jpg'),
(31, 18, 'Harmonização - Terceira Taça', 'Vinho para sobremesa', 38.90, 'vinho_sobremesa.jpg'),
(31, 14, 'Café Especial da Casa', 'Café selecionado do cerrado', 14.90, 'cafe_especial.jpg'),
(31, 14, 'Infusão de Ervas', 'Chá de ervas frescas', 16.90, 'infusao_ervas.jpg'),

(32, 1, 'Burrata com Tomates Confit', 'Burrata com tomates e pesto', 52.90, 'burrata_tomates_confit.jpg'),
(32, 1, 'Tartar de Atum com Abacate', 'Atum picado com abacate e gergelim', 58.90, 'tartar_atum_abacate.jpg'),
(32, 1, 'Ceviche de Peixe Branco', 'Peixe marinado com leite de tigre', 46.90, 'ceviche_peixe_branco.jpg'),
(32, 2, 'Salada de Figos com Prosciutto', 'Figos frescos com presunto parma', 48.90, 'salada_figos_prosciutto.jpg'),
(32, 2, 'Salada de Lentilha com Salmão', 'Lentilha com salmão defumado', 54.90, 'salada_lentilha_salmao.jpg'),
(32, 4, 'Wagyu Grelhado', 'Carne wagyu com sal grosso', 158.90, 'wagyu_grelhado.jpg'),
(32, 4, 'Pato à L''Orange', 'Pato com molho de laranja', 98.90, 'pato_orange.jpg'),
(32, 4, 'Fillet Rossini', 'Filé mignon com foie gras', 128.90, 'fillet_rossini.jpg'),
(32, 4, 'Rack de Cordeiro', 'Carré de cordeiro com ervas', 112.90, 'rack_cordeiro.jpg'),
(32, 10, 'Lagosta Thermidor', 'Lagosta gratinada', 168.90, 'lagosta_thermidor.jpg'),
(32, 10, 'Salmão com Crosta de Pistache', 'Salmão com pistache e mel', 86.90, 'salmao_pistache.jpg'),
(32, 11, 'Risoto de Lagosta', 'Risoto com pedaços de lagosta', 92.90, 'risoto_lagosta.jpg'),
(32, 11, 'Risoto de Alcachofra', 'Risoto com alcachofra e limão', 68.90, 'risoto_alcachofra.jpg'),
(32, 5, 'Tagliatelle ao Funghi Porcini', 'Massa fresca com cogumelos porcini', 72.90, 'tagliatelle_porcini.jpg'),
(32, 5, 'Ravioli de Trufa', 'Ravioli recheado com trufa', 88.90, 'ravioli_trufa.jpg'),
(32, 12, 'Gratin de Batata com Queijo', 'Batata gratinada com queijos', 38.90, 'gratin_batata_queijo.jpg'),
(32, 12, 'Aspargos Grelhados', 'Aspargos com azeite e limão', 42.90, 'aspargos_grelhados.jpg'),
(32, 13, 'Chocolate Sphere', 'Esfera de chocolate com sorvete', 45.90, 'chocolate_sphere.jpg'),
(32, 13, 'Cheesecake de Maracujá', 'Cheesecake com calda de maracujá', 38.90, 'cheesecake_maracuja.jpg'),
(32, 13, 'Semifreddo de Café', 'Semifreddo de café com amaretto', 42.90, 'semifreddo_cafe.jpg'),
(32, 17, 'Signature Cocktail', 'Coquetel exclusivo da casa', 32.90, 'signature_cocktail.jpg'),
(32, 17, 'Martini Clássico', 'Martini com azeitonas', 28.90, 'martini_classico.jpg'),
(32, 18, 'Vinho de Autor', 'Vinho selecionado pelo sommelier', 65.90, 'vinho_autor.jpg'),
(32, 18, 'Espumante Francês', 'Champagne premium', 125.90, 'champagne_premium.jpg'),
(32, 14, 'Café com Licor', 'Café com licor de amaretto', 24.90, 'cafe_licor.jpg'),
(32, 14, 'Chá da Noite', 'Blend especial para finalizar', 18.90, 'cha_noite.jpg');