<?php
// usuarios.inc.php - Conteúdo da view
?>
<main class="main-content">
    <!-- Header Controls (Add Button Only) -->
    <div class="header-controls" style="display: flex; justify-content: flex-start; align-items: center; margin-bottom: 2rem;">
        <button class="btn-save" id="btnNovoUsuario" style="width: 100%; max-width: 300px; padding: 1rem; font-size: 1.1rem;">+ Novo Usuário</button>
    </div>

    <!-- Page Title -->
    <h2 class="order-list-title">Gestão de Usuários</h2>

    <!-- Users Grid -->
    <div class="users-grid" id="usersGrid">
        <!-- User cards will be generated by JavaScript/PHP -->
            <!-- Exemplo estático para visualização -->
        <div class="user-card">
            <div class="user-avatar">AD</div>
            <div class="user-info">
                <h3>Admin Default</h3>
                <p>admin@ordox.com</p>
                <span class="user-role">Admin</span>
            </div>
            <div class="user-actions">
                <button class="btn-edit">Editar</button>
                <button class="btn-delete">Excluir</button>
            </div>
        </div>
    </div>
</main>

<!-- Modal -->
<div class="modal-overlay" id="modalOverlay">
    <div class="modal">
        <div class="modal-header">
            <h2 id="modalTitle">Adicionar Novo Usuário</h2>
            <button class="modal-close" id="modalClose">
                <svg viewBox="0 0 24 24" fill="none">
                    <path d="M18 6L6 18M6 6l12 12" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                </svg>
            </button>
        </div>
        <div class="modal-body">
            <form id="formUsuario">
                <input type="hidden" id="userId" name="id">
                
                <div class="form-group">
                    <label for="userName">Nome</label>
                    <input type="text" id="userName" name="nome" placeholder="Nome completo" required>
                </div>
                
                <div class="form-group">
                    <label for="userEmail">Email</label>
                    <input type="email" id="userEmail" name="email" placeholder="email@exemplo.com" required>
                </div>

                <div class="form-group">
                    <label for="userPassword">Senha</label>
                    <input type="password" id="userPassword" name="senha" placeholder="********">
                    <small style="color: #666; font-size: 0.8em;">Deixe em branco para manter a atual (na edição)</small>
                </div>
                
                <div class="form-group">
                    <label for="userRole">Cargo</label>
                    <select id="userRole" name="cargo" required>
                        <option value="admin">Admin</option>
                        <option value="gerente">Gerente</option>
                        <option value="funcionario">Funcionário</option>
                    </select>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button class="btn-cancel" id="btnCancelar">Cancelar</button>
            <button class="btn-save" id="btnSalvar">Salvar Usuário</button>
        </div>
    </div>
</div>

<script>
    // Script inline para inicialização rápida e lógica específica da view
    $(document).ready(function() {
        // Modal controls
        const $modal = $('#modalOverlay');
        
        $('#btnNovoUsuario').click(function() {
            $('#modalTitle').text('Adicionar Novo Usuário');
            $('#formUsuario')[0].reset();
            $('#userId').val('');
            $modal.addClass('active'); // Assumindo que a classe active mostra o modal no CSS original ou ajustado
            $modal.css('display', 'flex'); // Força display flex caso o CSS use display: none
        });

        $('#modalClose, #btnCancelar').click(function() {
            $modal.removeClass('active');
            $modal.css('display', 'none');
        });

        $('#btnSalvar').click(function() {
            // Aqui virá a lógica AJAX para salvar
            const formData = $('#formUsuario').serialize();
            console.log('Salvando...', formData);
            // Exemplo de AJAX:
            /*
            $.post('api/usuarios/salvar', formData, function(response) {
                // Atualizar grid
                $modal.css('display', 'none');
            });
            */
        });

        // Fechar modal ao clicar fora
        $modal.click(function(e) {
            if (e.target === this) {
                $(this).css('display', 'none');
            }
        });
    });
</script>
