<?php
// usuarios.inc.php - Conteúdo da view
?>
<main class="main-content">
    <!-- Header Controls (Add Button Only) -->
    <div class="header-controls" style="display: flex; justify-content: flex-start; align-items: center; margin-bottom: 2rem;">
        <button class="btn-save" id="btnNovoUsuario" style="width: 100%; max-width: 300px; padding: 1rem; font-size: 1.1rem;">+ Novo Usuário</button>
    </div>

    <!-- Page Title -->
    <h2 class="order-list-title">Gestão de Usuários</h2>

    <!-- Users Grid -->
    <div class="users-grid" id="usersGrid">
        <!-- User cards will be generated by JavaScript -->
        <div style="text-align: center; padding: 2rem;">
            <p>Carregando usuários...</p>
        </div>
    </div>
</main>

<!-- Modal -->
<div class="modal-overlay" id="modalOverlay">
    <div class="modal">
        <div class="modal-header">
            <h2 id="modalTitle">Adicionar Novo Usuário</h2>
            <button class="modal-close" id="modalClose">
                <svg viewBox="0 0 24 24" fill="none">
                    <path d="M18 6L6 18M6 6l12 12" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                </svg>
            </button>
        </div>
        <div class="modal-body">
            <form id="formUsuario" action="<?= $URL->getBase(); ?>admin/usuarios/salvar" method="POST">
                <input type="hidden" id="userId" name="id">
                
                <div class="form-group">
                    <label for="userName">Nome</label>
                    <input type="text" id="userName" name="nome" placeholder="Nome completo" required>
                </div>
                
                <div class="form-group">
                    <label for="userEmail">Email</label>
                    <input type="email" id="userEmail" name="email" placeholder="email@exemplo.com" required>
                </div>

                <div class="form-group">
                    <label for="userPassword">Senha</label>
                    <input type="password" id="userPassword" name="senha" placeholder="********">
                    <small style="color: #666; font-size: 0.8em;">Deixe em branco para manter a atual (na edição)</small>
                </div>
                
                <div class="form-group">
                    <label for="userRole">Cargo</label>
                    <select id="userRole" name="cargo" required>
                        <option value="admin">Admin</option>
                        <option value="gerente">Gerente</option>
                        <option value="funcionario">Funcionário</option>
                    </select>
                </div>
            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn-cancel" id="btnCancelar">Cancelar</button>
            <button type="button" class="btn-save" id="btnSalvar">Salvar Usuário</button>
        </div>
    </div>
</div>

<!-- Modal de confirmação de exclusão -->
<div class="modal-overlay" id="modalDeleteOverlay">
    <div class="modal">
        <div class="modal-header">
            <h2>Excluir Usuário</h2>
            <button class="modal-close" id="modalDeleteClose">
                <svg viewBox="0 0 24 24" fill="none">
                    <path d="M18 6L6 18M6 6l12 12" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                </svg>
            </button>
        </div>
        <div class="modal-body">
            <p id="deleteMessage">Deseja realmente excluir este usuário?</p>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn-cancel" id="btnDeleteCancel">Não</button>
            <button type="button" class="btn-delete" id="btnDeleteConfirm">Sim</button>
        </div>
    </div>
</div>

<script>
    // Script inline para inicialização rápida e lógica específica da view
    // Aguarda jQuery e main.js estarem prontos
    $(document).ready(function() {
        console.log("usuarios.inc.php script carregado");
        
        const $modal = $('#modalOverlay');
        const baseUrl = '<?= $URL->getBase(); ?>';
        const $deleteModal = $('#modalDeleteOverlay');
        
        // Carregar lista de usuários ao carregar a página
        loadUsuarios();
        
        // Modal controls
        $('#btnNovoUsuario').click(function() {
            $('#modalTitle').text('Adicionar Novo Usuário');
            $('#formUsuario')[0].reset();
            $('#userId').val('');
            $('#userPassword').attr('required', true);
            $modal.addClass('active');
            $modal.css('display', 'flex');
        });

        $('#modalClose, #btnCancelar').click(function() {
            $modal.removeClass('active');
            $modal.css('display', 'none');
        });

        // Botão Salvar - o submit será tratado pelo main.js
        $('#btnSalvar').off('click').on('click', function(e) {
            e.preventDefault();
            e.stopPropagation();
            console.log("Botão Salvar clicado");
            
            // Valida o form antes de enviar
            if ($('#formUsuario')[0].checkValidity()) {
                console.log("Form válido, enviando...");
                $('#formUsuario').submit();
            } else {
                console.log("Form inválido");
                $('#formUsuario')[0].reportValidity();
            }
            
            return false;
        });

        // Fechar modal ao clicar fora
        $modal.click(function(e) {
            if (e.target === this) {
                $(this).css('display', 'none');
            }
        });

        // Função para carregar usuários
        function loadUsuarios() {
            $.ajax({
                url: baseUrl + 'admin/usuarios/listar',
                method: 'GET',
                dataType: 'json',
                success: function(response) {
                    if (response.success && response.data) {
                        renderUsuarios(response.data);
                    } else {
                        $('#usersGrid').html('<div style="text-align: center; padding: 2rem;"><p>Nenhum usuário encontrado.</p></div>');
                    }
                },
                error: function() {
                    $('#usersGrid').html('<div style="text-align: center; padding: 2rem;"><p style="color: red;">Erro ao carregar usuários.</p></div>');
                }
            });
        }

        // Função para renderizar usuários no grid
        function renderUsuarios(usuarios) {
            if (!usuarios || usuarios.length === 0) {
                $('#usersGrid').html('<div style="text-align: center; padding: 2rem;"><p>Nenhum usuário cadastrado.</p></div>');
                return;
            }

            let html = '';
            usuarios.forEach(function(usuario) {
                const iniciais = usuario.nome ? usuario.nome.substring(0, 2).toUpperCase() : 'U';
                const cargo = usuario.cargo || 'N/A';
                const cargoLabel = cargo.charAt(0).toUpperCase() + cargo.slice(1);
                const encodedName = encodeURIComponent(usuario.nome || '');
                
                html += `
                    <div class="user-card" data-id="${usuario.id}">
                        <div class="user-avatar">${iniciais}</div>
                        <div class="user-info">
                            <h3>${usuario.nome || 'Sem nome'}</h3>
                            <p>${usuario.email || 'Sem email'}</p>
                            <span class="user-role">${cargoLabel}</span>
                        </div>
                        <div class="user-actions">
                            <button type="button" class="btn-edit" data-id="${usuario.id}" title="Editar usuário">Editar</button>
                            <button type="button" class="btn-delete" data-id="${usuario.id}" data-name="${encodedName}" title="Excluir usuário">Excluir</button>
                        </div>
                    </div>
                `;
            });
            
            $('#usersGrid').html(html);
        }

        // Eventos dos botões (delegados)
        $(document).on('click', '.btn-edit', function() {
            const id = $(this).data('id');
            abrirEdicaoUsuario(id);
        });

        $(document).on('click', '.btn-delete', function() {
            const id = $(this).data('id');
            const nome = decodeURIComponent($(this).data('name') || '');
            abrirModalExcluir(id, nome);
        });

        let usuarioExcluirId = null;

        // Função para editar usuário
        function abrirEdicaoUsuario(id) {
            if (!id || id <= 0) {
                Default.message('ID de usuário inválido.', 3000, 'error');
                return;
            }
            
            console.log("Editando usuário ID:", id);
            
            $.ajax({
                url: baseUrl + 'admin/usuarios/buscar?id=' + id,
                method: 'GET',
                dataType: 'json',
                success: function(response) {
                    console.log("Resposta buscar usuário:", response);
                    
                    if (response && response.success && response.data) {
                        const usuario = response.data;
                        
                        // Preenche o formulário
                        $('#modalTitle').text('Editar Usuário');
                        $('#userId').val(usuario.id);
                        $('#userName').val(usuario.nome || '');
                        $('#userEmail').val(usuario.email || '');
                        $('#userRole').val(usuario.cargo || 'admin');
                        $('#userPassword').val('').removeAttr('required');
                        
                        // Abre o modal
                        $modal.addClass('active');
                        $modal.css('display', 'flex');
                        
                        console.log("Modal aberto para edição");
                    } else {
                        var msg = (response && response.message) ? response.message : 'Erro ao carregar usuário.';
                        Default.message(msg, 3000, 'error');
                    }
                },
                error: function(xhr, status, error) {
                    console.log("Erro ao buscar usuário:", xhr.responseText, status, error);
                    
                    // Tenta parsear resposta de erro
                    var retorno = null;
                    try {
                        if (xhr.responseText && xhr.responseText.trim() !== '') {
                            retorno = JSON.parse(xhr.responseText);
                        }
                    } catch (e) {
                        // Não é JSON
                    }
                    
                    var msg = (retorno && retorno.message) ? retorno.message : 'Erro ao carregar usuário.';
                    Default.message(msg, 3000, 'error');
                }
            });
        }

        function abrirModalExcluir(id, nome) {
            if (!id || id <= 0) {
                Default.message('ID de usuário inválido.', 3000, 'error');
                return;
            }
            usuarioExcluirId = id;
            const mensagem = nome ? `Deseja realmente excluir o usuário <strong>${nome}</strong>?` : 'Deseja realmente excluir este usuário?';
            $('#deleteMessage').html(mensagem);
            $deleteModal.addClass('active').css('display', 'flex');
        }

        function fecharModalExcluir() {
            usuarioExcluirId = null;
            $deleteModal.removeClass('active').css('display', 'none');
        }

        $('#modalDeleteClose, #btnDeleteCancel').on('click', function() {
            fecharModalExcluir();
        });

        // Fecha modal ao clicar fora
        $deleteModal.on('click', function(e) {
            if (e.target === this) {
                fecharModalExcluir();
            }
        });

        $('#btnDeleteConfirm').on('click', function() {
    const $confirmBtn = $(this);
    $confirmBtn.prop('disabled', true).text('Excluindo...');
    if (!usuarioExcluirId) {
        Default.message('Nenhum usuário selecionado.', 3000, 'error');
        $confirmBtn.prop('disabled', false).text('Sim');
        return;
    }

    fecharModalExcluir(); // FECHA O MODAL IMEDIATAMENTE

    $.ajax({
        url: baseUrl + 'admin/usuarios/excluir',
        method: 'POST',
        data: {
            id: usuarioExcluirId
        },
        dataType: 'json',
        success: function(response) {
            Default.message(response.message || 'Usuário excluído com sucesso!', 3000, response.type || 'success');
            setTimeout(function(){
                loadUsuarios();
            }, 500);
        },
        error: function(xhr) {
            let msg = 'Erro ao excluir usuário.';
            try {
                const ret = JSON.parse(xhr.responseText);
                if (ret && ret.message) {
                    msg = ret.message;
                }
            } catch (e) {}
            Default.message(msg, 3000, 'error');
        },
        complete: function() {
            $confirmBtn.prop('disabled', false).text('Sim');
        }
    });
});
        // Atualizar grid após salvar (será chamado pelo main.js após sucesso)
        $(document).on('usuarioSalvo', function() {
            loadUsuarios();
            $modal.removeClass('active');
            $modal.css('display', 'none');
        });
    });
</script>
